/* Generated by Yosys 0.7+574 (git sha1 0fad1570, gcc 6.3.0-18+deb9u1 -fPIC -Os) */

(* top =  1  *)
(* src = "arbitroEstructural.v:4" *)
module arbitroEstructural(clk, reset_L, VC0_p0, VC1_p0, VC0_p1, VC1_p1, validBits, emptyVC0_p0, emptyVC1_p0, emptyVC0_p1, emptyVC1_p1, popVC0_0, popVC1_0, popVC0_1, popVC1_1, dataOut_0, dataOut_1);
  (* src = "arbitroEstructural.v:47" *)
  wire [4:0] _000_;
  (* src = "arbitroEstructural.v:47" *)
  wire [4:0] _001_;
  (* src = "arbitroEstructural.v:47" *)
  wire [5:0] _002_;
  (* src = "arbitroEstructural.v:47" *)
  wire [4:0] _003_;
  (* src = "arbitroEstructural.v:47" *)
  wire [4:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  (* src = "arbitroEstructural.v:6" *)
  input [4:0] VC0_p0;
  (* src = "arbitroEstructural.v:8" *)
  input [4:0] VC0_p1;
  (* src = "arbitroEstructural.v:7" *)
  input [4:0] VC1_p0;
  (* src = "arbitroEstructural.v:9" *)
  input [4:0] VC1_p1;
  (* src = "arbitroEstructural.v:4" *)
  input clk;
  (* src = "arbitroEstructural.v:19" *)
  output [4:0] dataOut_0;
  (* src = "arbitroEstructural.v:20" *)
  output [4:0] dataOut_1;
  (* src = "arbitroEstructural.v:11" *)
  input emptyVC0_p0;
  (* src = "arbitroEstructural.v:13" *)
  input emptyVC0_p1;
  (* src = "arbitroEstructural.v:12" *)
  input emptyVC1_p0;
  (* src = "arbitroEstructural.v:14" *)
  input emptyVC1_p1;
  (* src = "arbitroEstructural.v:27" *)
  wire [5:0] muxMultiOut;
  (* src = "arbitroEstructural.v:26" *)
  wire [4:0] muxVC0_muxMulti;
  (* src = "arbitroEstructural.v:26" *)
  wire [4:0] muxVC1_muxMulti;
  (* src = "arbitroEstructural.v:15" *)
  output popVC0_0;
  (* src = "arbitroEstructural.v:17" *)
  output popVC0_1;
  (* src = "arbitroEstructural.v:16" *)
  output popVC1_0;
  (* src = "arbitroEstructural.v:18" *)
  output popVC1_1;
  (* src = "arbitroEstructural.v:23" *)
  wire request0_VC0;
  (* src = "arbitroEstructural.v:23" *)
  wire request0_VC1;
  (* src = "arbitroEstructural.v:23" *)
  wire request1_VC0;
  (* src = "arbitroEstructural.v:23" *)
  wire request1_VC1;
  (* src = "arbitroEstructural.v:5" *)
  input reset_L;
  (* src = "arbitroEstructural.v:24" *)
  wire selectMUX_VC0;
  (* src = "arbitroEstructural.v:24" *)
  wire selectMUX_VC1;
  (* src = "arbitroEstructural.v:10" *)
  input [3:0] validBits;
  (* src = "arbitroEstructural.v:34" *)
  wire validMux_VC0;
  (* src = "arbitroEstructural.v:25" *)
  (* unused_bits = "0" *)
  wire validMux_VC1;
  NOT _107_ (
    .A(VC0_p1[1]),
    .Y(_092_)
  );
  NOT _108_ (
    .A(VC0_p1[2]),
    .Y(_093_)
  );
  NOT _109_ (
    .A(VC0_p1[3]),
    .Y(_094_)
  );
  NOT _110_ (
    .A(VC0_p1[4]),
    .Y(_095_)
  );
  NOT _111_ (
    .A(VC1_p1[0]),
    .Y(_096_)
  );
  NOT _112_ (
    .A(VC1_p1[1]),
    .Y(_097_)
  );
  NOT _113_ (
    .A(VC1_p1[2]),
    .Y(_098_)
  );
  NOT _114_ (
    .A(VC1_p1[3]),
    .Y(_099_)
  );
  NOT _115_ (
    .A(VC1_p1[4]),
    .Y(_100_)
  );
  NOT _116_ (
    .A(muxVC1_muxMulti[0]),
    .Y(_101_)
  );
  NOT _117_ (
    .A(muxVC1_muxMulti[1]),
    .Y(_102_)
  );
  NOT _118_ (
    .A(muxVC1_muxMulti[2]),
    .Y(_103_)
  );
  NOT _119_ (
    .A(muxVC1_muxMulti[3]),
    .Y(_104_)
  );
  NOT _120_ (
    .A(muxVC1_muxMulti[4]),
    .Y(_105_)
  );
  NOT _121_ (
    .A(muxMultiOut[0]),
    .Y(_106_)
  );
  NOT _122_ (
    .A(muxMultiOut[1]),
    .Y(_005_)
  );
  NOT _123_ (
    .A(muxMultiOut[2]),
    .Y(_006_)
  );
  NOT _124_ (
    .A(muxMultiOut[3]),
    .Y(_007_)
  );
  NOT _125_ (
    .A(muxMultiOut[5]),
    .Y(_008_)
  );
  NOT _126_ (
    .A(dataOut_0[0]),
    .Y(_009_)
  );
  NOT _127_ (
    .A(dataOut_0[1]),
    .Y(_010_)
  );
  NOT _128_ (
    .A(dataOut_0[2]),
    .Y(_011_)
  );
  NOT _129_ (
    .A(dataOut_0[3]),
    .Y(_012_)
  );
  NOT _130_ (
    .A(dataOut_0[4]),
    .Y(_013_)
  );
  NOT _131_ (
    .A(emptyVC0_p0),
    .Y(request0_VC0)
  );
  NOT _132_ (
    .A(emptyVC0_p1),
    .Y(request1_VC0)
  );
  NOT _133_ (
    .A(VC0_p1[0]),
    .Y(_014_)
  );
  NAND _134_ (
    .A(_101_),
    .B(validMux_VC0),
    .Y(_015_)
  );
  NAND _135_ (
    .A(validMux_VC0),
    .B(reset_L),
    .Y(_016_)
  );
  NOT _136_ (
    .A(_016_),
    .Y(_002_[5])
  );
  NAND _137_ (
    .A(reset_L),
    .B(_015_),
    .Y(_017_)
  );
  NOR _138_ (
    .A(muxVC0_muxMulti[0]),
    .B(validMux_VC0),
    .Y(_018_)
  );
  NOR _139_ (
    .A(_017_),
    .B(_018_),
    .Y(_002_[0])
  );
  NAND _140_ (
    .A(validMux_VC0),
    .B(_102_),
    .Y(_019_)
  );
  NAND _141_ (
    .A(reset_L),
    .B(_019_),
    .Y(_020_)
  );
  NOR _142_ (
    .A(validMux_VC0),
    .B(muxVC0_muxMulti[1]),
    .Y(_021_)
  );
  NOR _143_ (
    .A(_020_),
    .B(_021_),
    .Y(_002_[1])
  );
  NAND _144_ (
    .A(validMux_VC0),
    .B(_103_),
    .Y(_022_)
  );
  NAND _145_ (
    .A(reset_L),
    .B(_022_),
    .Y(_023_)
  );
  NOR _146_ (
    .A(validMux_VC0),
    .B(muxVC0_muxMulti[2]),
    .Y(_024_)
  );
  NOR _147_ (
    .A(_023_),
    .B(_024_),
    .Y(_002_[2])
  );
  NAND _148_ (
    .A(validMux_VC0),
    .B(_104_),
    .Y(_025_)
  );
  NAND _149_ (
    .A(reset_L),
    .B(_025_),
    .Y(_026_)
  );
  NOR _150_ (
    .A(validMux_VC0),
    .B(muxVC0_muxMulti[3]),
    .Y(_027_)
  );
  NOR _151_ (
    .A(_026_),
    .B(_027_),
    .Y(_002_[3])
  );
  NAND _152_ (
    .A(validMux_VC0),
    .B(_105_),
    .Y(_028_)
  );
  NAND _153_ (
    .A(reset_L),
    .B(_028_),
    .Y(_029_)
  );
  NOR _154_ (
    .A(validMux_VC0),
    .B(muxVC0_muxMulti[4]),
    .Y(_030_)
  );
  NOR _155_ (
    .A(_029_),
    .B(_030_),
    .Y(_002_[4])
  );
  NOR _156_ (
    .A(VC1_p0[0]),
    .B(selectMUX_VC1),
    .Y(_031_)
  );
  NAND _157_ (
    .A(_096_),
    .B(selectMUX_VC1),
    .Y(_032_)
  );
  NAND _158_ (
    .A(reset_L),
    .B(_032_),
    .Y(_033_)
  );
  NOR _159_ (
    .A(_031_),
    .B(_033_),
    .Y(_004_[0])
  );
  NOR _160_ (
    .A(selectMUX_VC1),
    .B(VC1_p0[1]),
    .Y(_034_)
  );
  NAND _161_ (
    .A(selectMUX_VC1),
    .B(_097_),
    .Y(_035_)
  );
  NAND _162_ (
    .A(reset_L),
    .B(_035_),
    .Y(_036_)
  );
  NOR _163_ (
    .A(_034_),
    .B(_036_),
    .Y(_004_[1])
  );
  NOR _164_ (
    .A(selectMUX_VC1),
    .B(VC1_p0[2]),
    .Y(_037_)
  );
  NAND _165_ (
    .A(selectMUX_VC1),
    .B(_098_),
    .Y(_038_)
  );
  NAND _166_ (
    .A(reset_L),
    .B(_038_),
    .Y(_039_)
  );
  NOR _167_ (
    .A(_037_),
    .B(_039_),
    .Y(_004_[2])
  );
  NOR _168_ (
    .A(selectMUX_VC1),
    .B(VC1_p0[3]),
    .Y(_040_)
  );
  NAND _169_ (
    .A(selectMUX_VC1),
    .B(_099_),
    .Y(_041_)
  );
  NAND _170_ (
    .A(reset_L),
    .B(_041_),
    .Y(_042_)
  );
  NOR _171_ (
    .A(_040_),
    .B(_042_),
    .Y(_004_[3])
  );
  NOR _172_ (
    .A(selectMUX_VC1),
    .B(VC1_p0[4]),
    .Y(_043_)
  );
  NAND _173_ (
    .A(selectMUX_VC1),
    .B(_100_),
    .Y(_044_)
  );
  NAND _174_ (
    .A(reset_L),
    .B(_044_),
    .Y(_045_)
  );
  NOR _175_ (
    .A(_043_),
    .B(_045_),
    .Y(_004_[4])
  );
  NOR _176_ (
    .A(selectMUX_VC0),
    .B(VC0_p0[0]),
    .Y(_046_)
  );
  NAND _177_ (
    .A(selectMUX_VC0),
    .B(_014_),
    .Y(_047_)
  );
  NAND _178_ (
    .A(reset_L),
    .B(_047_),
    .Y(_048_)
  );
  NOR _179_ (
    .A(_046_),
    .B(_048_),
    .Y(_003_[0])
  );
  NOR _180_ (
    .A(VC0_p0[1]),
    .B(selectMUX_VC0),
    .Y(_049_)
  );
  NAND _181_ (
    .A(_092_),
    .B(selectMUX_VC0),
    .Y(_050_)
  );
  NAND _182_ (
    .A(reset_L),
    .B(_050_),
    .Y(_051_)
  );
  NOR _183_ (
    .A(_049_),
    .B(_051_),
    .Y(_003_[1])
  );
  NOR _184_ (
    .A(selectMUX_VC0),
    .B(VC0_p0[2]),
    .Y(_052_)
  );
  NAND _185_ (
    .A(selectMUX_VC0),
    .B(_093_),
    .Y(_053_)
  );
  NAND _186_ (
    .A(reset_L),
    .B(_053_),
    .Y(_054_)
  );
  NOR _187_ (
    .A(_052_),
    .B(_054_),
    .Y(_003_[2])
  );
  NOR _188_ (
    .A(selectMUX_VC0),
    .B(VC0_p0[3]),
    .Y(_055_)
  );
  NAND _189_ (
    .A(selectMUX_VC0),
    .B(_094_),
    .Y(_056_)
  );
  NAND _190_ (
    .A(reset_L),
    .B(_056_),
    .Y(_057_)
  );
  NOR _191_ (
    .A(_055_),
    .B(_057_),
    .Y(_003_[3])
  );
  NOR _192_ (
    .A(selectMUX_VC0),
    .B(VC0_p0[4]),
    .Y(_058_)
  );
  NAND _193_ (
    .A(selectMUX_VC0),
    .B(_095_),
    .Y(_059_)
  );
  NAND _194_ (
    .A(reset_L),
    .B(_059_),
    .Y(_060_)
  );
  NOR _195_ (
    .A(_058_),
    .B(_060_),
    .Y(_003_[4])
  );
  NOR _196_ (
    .A(dataOut_1[0]),
    .B(muxMultiOut[4]),
    .Y(_061_)
  );
  NAND _197_ (
    .A(_106_),
    .B(muxMultiOut[4]),
    .Y(_062_)
  );
  NAND _198_ (
    .A(reset_L),
    .B(_062_),
    .Y(_063_)
  );
  NOR _199_ (
    .A(_061_),
    .B(_063_),
    .Y(_001_[0])
  );
  NOR _200_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[1]),
    .Y(_064_)
  );
  NAND _201_ (
    .A(muxMultiOut[4]),
    .B(_005_),
    .Y(_065_)
  );
  NAND _202_ (
    .A(reset_L),
    .B(_065_),
    .Y(_066_)
  );
  NOR _203_ (
    .A(_064_),
    .B(_066_),
    .Y(_001_[1])
  );
  NOR _204_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[2]),
    .Y(_067_)
  );
  NAND _205_ (
    .A(muxMultiOut[4]),
    .B(_006_),
    .Y(_068_)
  );
  NAND _206_ (
    .A(reset_L),
    .B(_068_),
    .Y(_069_)
  );
  NOR _207_ (
    .A(_067_),
    .B(_069_),
    .Y(_001_[2])
  );
  NOR _208_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[3]),
    .Y(_070_)
  );
  NAND _209_ (
    .A(muxMultiOut[4]),
    .B(_007_),
    .Y(_071_)
  );
  NAND _210_ (
    .A(reset_L),
    .B(_071_),
    .Y(_072_)
  );
  NOR _211_ (
    .A(_070_),
    .B(_072_),
    .Y(_001_[3])
  );
  NOR _212_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[4]),
    .Y(_073_)
  );
  NAND _213_ (
    .A(muxMultiOut[4]),
    .B(_008_),
    .Y(_074_)
  );
  NAND _214_ (
    .A(reset_L),
    .B(_074_),
    .Y(_075_)
  );
  NOR _215_ (
    .A(_073_),
    .B(_075_),
    .Y(_001_[4])
  );
  NOR _216_ (
    .A(muxMultiOut[0]),
    .B(muxMultiOut[4]),
    .Y(_076_)
  );
  NAND _217_ (
    .A(muxMultiOut[4]),
    .B(_009_),
    .Y(_077_)
  );
  NAND _218_ (
    .A(reset_L),
    .B(_077_),
    .Y(_078_)
  );
  NOR _219_ (
    .A(_076_),
    .B(_078_),
    .Y(_000_[0])
  );
  NOR _220_ (
    .A(muxMultiOut[4]),
    .B(muxMultiOut[1]),
    .Y(_079_)
  );
  NAND _221_ (
    .A(muxMultiOut[4]),
    .B(_010_),
    .Y(_080_)
  );
  NAND _222_ (
    .A(reset_L),
    .B(_080_),
    .Y(_081_)
  );
  NOR _223_ (
    .A(_079_),
    .B(_081_),
    .Y(_000_[1])
  );
  NOR _224_ (
    .A(muxMultiOut[4]),
    .B(muxMultiOut[2]),
    .Y(_082_)
  );
  NAND _225_ (
    .A(muxMultiOut[4]),
    .B(_011_),
    .Y(_083_)
  );
  NAND _226_ (
    .A(reset_L),
    .B(_083_),
    .Y(_084_)
  );
  NOR _227_ (
    .A(_082_),
    .B(_084_),
    .Y(_000_[2])
  );
  NOR _228_ (
    .A(muxMultiOut[4]),
    .B(muxMultiOut[3]),
    .Y(_085_)
  );
  NAND _229_ (
    .A(muxMultiOut[4]),
    .B(_012_),
    .Y(_086_)
  );
  NAND _230_ (
    .A(reset_L),
    .B(_086_),
    .Y(_087_)
  );
  NOR _231_ (
    .A(_085_),
    .B(_087_),
    .Y(_000_[3])
  );
  NOR _232_ (
    .A(muxMultiOut[4]),
    .B(muxMultiOut[5]),
    .Y(_088_)
  );
  NAND _233_ (
    .A(muxMultiOut[4]),
    .B(_013_),
    .Y(_089_)
  );
  NAND _234_ (
    .A(reset_L),
    .B(_089_),
    .Y(_090_)
  );
  NOR _235_ (
    .A(_088_),
    .B(_090_),
    .Y(_000_[4])
  );
  NAND _236_ (
    .A(emptyVC0_p0),
    .B(emptyVC0_p1),
    .Y(_091_)
  );
  NOR _237_ (
    .A(emptyVC1_p0),
    .B(_091_),
    .Y(request0_VC1)
  );
  NOR _238_ (
    .A(emptyVC1_p1),
    .B(_091_),
    .Y(request1_VC1)
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _239_ (
    .C(clk),
    .D(_000_[0]),
    .Q(dataOut_0[0])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _240_ (
    .C(clk),
    .D(_000_[1]),
    .Q(dataOut_0[1])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _241_ (
    .C(clk),
    .D(_000_[2]),
    .Q(dataOut_0[2])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _242_ (
    .C(clk),
    .D(_000_[3]),
    .Q(dataOut_0[3])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _243_ (
    .C(clk),
    .D(_000_[4]),
    .Q(dataOut_0[4])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _244_ (
    .C(clk),
    .D(_001_[0]),
    .Q(dataOut_1[0])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _245_ (
    .C(clk),
    .D(_001_[1]),
    .Q(dataOut_1[1])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _246_ (
    .C(clk),
    .D(_001_[2]),
    .Q(dataOut_1[2])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _247_ (
    .C(clk),
    .D(_001_[3]),
    .Q(dataOut_1[3])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _248_ (
    .C(clk),
    .D(_001_[4]),
    .Q(dataOut_1[4])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _249_ (
    .C(clk),
    .D(_003_[0]),
    .Q(muxVC0_muxMulti[0])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _250_ (
    .C(clk),
    .D(_003_[1]),
    .Q(muxVC0_muxMulti[1])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _251_ (
    .C(clk),
    .D(_003_[2]),
    .Q(muxVC0_muxMulti[2])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _252_ (
    .C(clk),
    .D(_003_[3]),
    .Q(muxVC0_muxMulti[3])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _253_ (
    .C(clk),
    .D(_003_[4]),
    .Q(muxVC0_muxMulti[4])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _254_ (
    .C(clk),
    .D(_004_[0]),
    .Q(muxVC1_muxMulti[0])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _255_ (
    .C(clk),
    .D(_004_[1]),
    .Q(muxVC1_muxMulti[1])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _256_ (
    .C(clk),
    .D(_004_[2]),
    .Q(muxVC1_muxMulti[2])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _257_ (
    .C(clk),
    .D(_004_[3]),
    .Q(muxVC1_muxMulti[3])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _258_ (
    .C(clk),
    .D(_004_[4]),
    .Q(muxVC1_muxMulti[4])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _259_ (
    .C(clk),
    .D(_002_[0]),
    .Q(muxMultiOut[0])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _260_ (
    .C(clk),
    .D(_002_[1]),
    .Q(muxMultiOut[1])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _261_ (
    .C(clk),
    .D(_002_[2]),
    .Q(muxMultiOut[2])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _262_ (
    .C(clk),
    .D(_002_[3]),
    .Q(muxMultiOut[3])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _263_ (
    .C(clk),
    .D(_002_[4]),
    .Q(muxMultiOut[4])
  );
  (* src = "arbitroEstructural.v:47" *)
  DFF _264_ (
    .C(clk),
    .D(_002_[5]),
    .Q(muxMultiOut[5])
  );
  (* src = "arbitroEstructural.v:29" *)
  roundRobinEstructural roundRobinEstructuralVC0 (
    .clk(clk),
    .pop_0(popVC0_0),
    .pop_1(popVC0_1),
    .portMux(selectMUX_VC0),
    .request0(request0_VC0),
    .request1(request1_VC0),
    .reset_L(reset_L),
    .validMux(validMux_VC0)
  );
  (* src = "arbitroEstructural.v:38" *)
  roundRobinEstructural roundRobinEstructuralVC1 (
    .clk(clk),
    .pop_0(popVC1_0),
    .pop_1(popVC1_1),
    .portMux(selectMUX_VC1),
    .request0(request0_VC1),
    .request1(request1_VC1),
    .reset_L(reset_L),
    .validMux(validMux_VC1)
  );
endmodule

(* src = "roundRobinEstructural.v:1" *)
module roundRobinEstructural(clk, reset_L, request0, request1, portMux, validMux, pop_0, pop_1);
  (* src = "roundRobinEstructural.v:12" *)
  wire _00_;
  (* src = "roundRobinEstructural.v:12" *)
  wire _01_;
  (* src = "roundRobinEstructural.v:12" *)
  wire _02_;
  (* src = "roundRobinEstructural.v:12" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "roundRobinEstructural.v:1" *)
  input clk;
  (* src = "roundRobinEstructural.v:7" *)
  output pop_0;
  (* src = "roundRobinEstructural.v:8" *)
  output pop_1;
  (* src = "roundRobinEstructural.v:5" *)
  output portMux;
  (* src = "roundRobinEstructural.v:3" *)
  input request0;
  (* src = "roundRobinEstructural.v:4" *)
  input request1;
  (* src = "roundRobinEstructural.v:2" *)
  input reset_L;
  (* src = "roundRobinEstructural.v:6" *)
  output validMux;
  NOT _14_ (
    .A(request0),
    .Y(_13_)
  );
  NOR _15_ (
    .A(portMux),
    .B(_13_),
    .Y(_04_)
  );
  NAND _16_ (
    .A(request1),
    .B(reset_L),
    .Y(_05_)
  );
  NOR _17_ (
    .A(_04_),
    .B(_05_),
    .Y(_01_)
  );
  NAND _18_ (
    .A(request1),
    .B(portMux),
    .Y(_06_)
  );
  NOT _19_ (
    .A(_06_),
    .Y(_07_)
  );
  NAND _20_ (
    .A(reset_L),
    .B(request0),
    .Y(_08_)
  );
  NOR _21_ (
    .A(request1),
    .B(request0),
    .Y(_09_)
  );
  NOR _22_ (
    .A(_07_),
    .B(_08_),
    .Y(_00_)
  );
  NAND _23_ (
    .A(reset_L),
    .B(_09_),
    .Y(_10_)
  );
  NOT _24_ (
    .A(_10_),
    .Y(_03_)
  );
  NAND _25_ (
    .A(portMux),
    .B(request0),
    .Y(_11_)
  );
  NOT _26_ (
    .A(_11_),
    .Y(_12_)
  );
  NOR _27_ (
    .A(_05_),
    .B(_12_),
    .Y(_02_)
  );
  (* src = "roundRobinEstructural.v:12" *)
  DFF _28_ (
    .C(clk),
    .D(_02_),
    .Q(portMux)
  );
  (* src = "roundRobinEstructural.v:12" *)
  DFF _29_ (
    .C(clk),
    .D(_03_),
    .Q(validMux)
  );
  (* src = "roundRobinEstructural.v:12" *)
  DFF _30_ (
    .C(clk),
    .D(_00_),
    .Q(pop_0)
  );
  (* src = "roundRobinEstructural.v:12" *)
  DFF _31_ (
    .C(clk),
    .D(_01_),
    .Q(pop_1)
  );
endmodule
