/* Generated by Yosys 0.7+574 (git sha1 0fad1570, gcc 6.3.0-18+deb9u1 -fPIC -Os) */

(* top =  1  *)
(* src = "roundRobinEstructural.v:1" *)
module roundRobinEstructural(clk, reset_L, request0, request1, portMux, validMux, pop_0, pop_1);
  (* src = "roundRobinEstructural.v:12" *)
  wire _00_;
  (* src = "roundRobinEstructural.v:12" *)
  wire _01_;
  (* src = "roundRobinEstructural.v:12" *)
  wire _02_;
  (* src = "roundRobinEstructural.v:12" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "roundRobinEstructural.v:1" *)
  input clk;
  (* src = "roundRobinEstructural.v:7" *)
  output pop_0;
  (* src = "roundRobinEstructural.v:8" *)
  output pop_1;
  (* src = "roundRobinEstructural.v:5" *)
  output portMux;
  (* src = "roundRobinEstructural.v:3" *)
  input request0;
  (* src = "roundRobinEstructural.v:4" *)
  input request1;
  (* src = "roundRobinEstructural.v:2" *)
  input reset_L;
  (* src = "roundRobinEstructural.v:6" *)
  output validMux;
  NOT _14_ (
    .A(request0),
    .Y(_13_)
  );
  NOR _15_ (
    .A(portMux),
    .B(_13_),
    .Y(_04_)
  );
  NAND _16_ (
    .A(request1),
    .B(reset_L),
    .Y(_05_)
  );
  NOR _17_ (
    .A(_04_),
    .B(_05_),
    .Y(_01_)
  );
  NAND _18_ (
    .A(request1),
    .B(portMux),
    .Y(_06_)
  );
  NOT _19_ (
    .A(_06_),
    .Y(_07_)
  );
  NAND _20_ (
    .A(reset_L),
    .B(request0),
    .Y(_08_)
  );
  NOR _21_ (
    .A(request1),
    .B(request0),
    .Y(_09_)
  );
  NOR _22_ (
    .A(_07_),
    .B(_08_),
    .Y(_00_)
  );
  NAND _23_ (
    .A(reset_L),
    .B(_09_),
    .Y(_10_)
  );
  NOT _24_ (
    .A(_10_),
    .Y(_03_)
  );
  NAND _25_ (
    .A(portMux),
    .B(request0),
    .Y(_11_)
  );
  NOT _26_ (
    .A(_11_),
    .Y(_12_)
  );
  NOR _27_ (
    .A(_05_),
    .B(_12_),
    .Y(_02_)
  );
  (* src = "roundRobinEstructural.v:12" *)
  DFF _28_ (
    .C(clk),
    .D(_02_),
    .Q(portMux)
  );
  (* src = "roundRobinEstructural.v:12" *)
  DFF _29_ (
    .C(clk),
    .D(_03_),
    .Q(validMux)
  );
  (* src = "roundRobinEstructural.v:12" *)
  DFF _30_ (
    .C(clk),
    .D(_00_),
    .Q(pop_0)
  );
  (* src = "roundRobinEstructural.v:12" *)
  DFF _31_ (
    .C(clk),
    .D(_01_),
    .Q(pop_1)
  );
endmodule
