/* Generated by Yosys 0.7+574 (git sha1 0fad1570, gcc 6.3.0-18+deb9u1 -fPIC -Os) */

module FIFOSynth(clk, reset, pop, push, valid, data_in, umbralA, umbralB, pause, continua, empty, fifo_error, almost_full, almost_empty, data_out, filled, rd_ptr, wr_ptr, valid_out);
  wire [2:0] _000_;
  wire [7:0] _001_;
  wire _002_;
  wire [2:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  output almost_empty;
  output almost_full;
  input clk;
  output continua;
  input [4:0] data_in;
  output [4:0] data_out;
  output empty;
  output fifo_error;
  output [3:0] filled;
  output pause;
  input pop;
  input push;
  output [2:0] rd_ptr;
  input reset;
  wire [4:0] to_fifo;
  input [3:0] umbralA;
  input [3:0] umbralB;
  input valid;
  wire [7:0] valid_bus;
  output valid_out;
  output [2:0] wr_ptr;
  NOT _170_ (
    .A(wr_ptr[0]),
    .Y(_134_)
  );
  NOT _171_ (
    .A(wr_ptr[2]),
    .Y(_135_)
  );
  NOT _172_ (
    .A(wr_ptr[1]),
    .Y(_136_)
  );
  NOT _173_ (
    .A(valid),
    .Y(_137_)
  );
  NOT _174_ (
    .A(reset),
    .Y(_138_)
  );
  NOT _175_ (
    .A(valid_bus[4]),
    .Y(_139_)
  );
  NOT _176_ (
    .A(valid_bus[3]),
    .Y(_140_)
  );
  NOT _177_ (
    .A(valid_bus[0]),
    .Y(_141_)
  );
  NOT _178_ (
    .A(rd_ptr[1]),
    .Y(_142_)
  );
  NOT _179_ (
    .A(rd_ptr[2]),
    .Y(_143_)
  );
  NOT _180_ (
    .A(rd_ptr[0]),
    .Y(_144_)
  );
  NOT _181_ (
    .A(umbralB[1]),
    .Y(_145_)
  );
  NOT _182_ (
    .A(umbralB[2]),
    .Y(_146_)
  );
  NOT _183_ (
    .A(umbralA[1]),
    .Y(_147_)
  );
  NOT _184_ (
    .A(umbralA[2]),
    .Y(_148_)
  );
  NOR _185_ (
    .A(wr_ptr[0]),
    .B(_144_),
    .Y(_149_)
  );
  NAND _186_ (
    .A(_134_),
    .B(rd_ptr[0]),
    .Y(_150_)
  );
  NOR _187_ (
    .A(_134_),
    .B(rd_ptr[0]),
    .Y(_151_)
  );
  NOR _188_ (
    .A(_149_),
    .B(_151_),
    .Y(_152_)
  );
  NOT _189_ (
    .A(_152_),
    .Y(filled[0])
  );
  NOR _190_ (
    .A(wr_ptr[1]),
    .B(rd_ptr[1]),
    .Y(_153_)
  );
  NOT _191_ (
    .A(_153_),
    .Y(_154_)
  );
  NOR _192_ (
    .A(_136_),
    .B(_142_),
    .Y(_155_)
  );
  NAND _193_ (
    .A(wr_ptr[1]),
    .B(rd_ptr[1]),
    .Y(_156_)
  );
  NOR _194_ (
    .A(_153_),
    .B(_155_),
    .Y(_157_)
  );
  NAND _195_ (
    .A(_154_),
    .B(_156_),
    .Y(_158_)
  );
  NAND _196_ (
    .A(_150_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _197_ (
    .A(_149_),
    .B(_157_),
    .Y(_160_)
  );
  NAND _198_ (
    .A(_159_),
    .B(_160_),
    .Y(_161_)
  );
  NOT _199_ (
    .A(_161_),
    .Y(filled[1])
  );
  NOR _200_ (
    .A(wr_ptr[0]),
    .B(wr_ptr[1]),
    .Y(_162_)
  );
  NAND _201_ (
    .A(_134_),
    .B(_136_),
    .Y(_163_)
  );
  NAND _202_ (
    .A(_142_),
    .B(rd_ptr[0]),
    .Y(_164_)
  );
  NOT _203_ (
    .A(_164_),
    .Y(_165_)
  );
  NOR _204_ (
    .A(_149_),
    .B(_156_),
    .Y(_166_)
  );
  NAND _205_ (
    .A(_150_),
    .B(_155_),
    .Y(_167_)
  );
  NOR _206_ (
    .A(_165_),
    .B(_166_),
    .Y(_168_)
  );
  NAND _207_ (
    .A(_164_),
    .B(_167_),
    .Y(_169_)
  );
  NOR _208_ (
    .A(_162_),
    .B(_168_),
    .Y(_004_)
  );
  NAND _209_ (
    .A(_163_),
    .B(_169_),
    .Y(_005_)
  );
  NOR _210_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .Y(_006_)
  );
  NOT _211_ (
    .A(_006_),
    .Y(_007_)
  );
  NOR _212_ (
    .A(wr_ptr[2]),
    .B(rd_ptr[2]),
    .Y(_008_)
  );
  NOT _213_ (
    .A(_008_),
    .Y(_009_)
  );
  NAND _214_ (
    .A(wr_ptr[2]),
    .B(rd_ptr[2]),
    .Y(_010_)
  );
  NOT _215_ (
    .A(_010_),
    .Y(_011_)
  );
  NOR _216_ (
    .A(_008_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _217_ (
    .A(_009_),
    .B(_010_),
    .Y(_013_)
  );
  NOR _218_ (
    .A(_007_),
    .B(_012_),
    .Y(_014_)
  );
  NAND _219_ (
    .A(_006_),
    .B(_013_),
    .Y(_015_)
  );
  NOR _220_ (
    .A(_006_),
    .B(_013_),
    .Y(_016_)
  );
  NAND _221_ (
    .A(_007_),
    .B(_012_),
    .Y(_017_)
  );
  NOR _222_ (
    .A(_014_),
    .B(_016_),
    .Y(_018_)
  );
  NAND _223_ (
    .A(_015_),
    .B(_017_),
    .Y(_019_)
  );
  NOR _224_ (
    .A(_005_),
    .B(_018_),
    .Y(_020_)
  );
  NOR _225_ (
    .A(_004_),
    .B(_019_),
    .Y(_021_)
  );
  NOR _226_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  NOT _227_ (
    .A(_022_),
    .Y(filled[2])
  );
  NOR _228_ (
    .A(_152_),
    .B(_161_),
    .Y(_023_)
  );
  NAND _229_ (
    .A(push),
    .B(_023_),
    .Y(_024_)
  );
  NOR _230_ (
    .A(_022_),
    .B(_024_),
    .Y(fifo_error)
  );
  NAND _231_ (
    .A(_152_),
    .B(_158_),
    .Y(_025_)
  );
  NOR _232_ (
    .A(_012_),
    .B(_025_),
    .Y(empty)
  );
  NOR _233_ (
    .A(umbralA[0]),
    .B(umbralA[1]),
    .Y(_026_)
  );
  NOT _234_ (
    .A(_026_),
    .Y(_027_)
  );
  NOR _235_ (
    .A(_148_),
    .B(_026_),
    .Y(_028_)
  );
  NOR _236_ (
    .A(_022_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _237_ (
    .A(umbralA[1]),
    .B(_158_),
    .Y(_030_)
  );
  NAND _238_ (
    .A(umbralA[0]),
    .B(_152_),
    .Y(_031_)
  );
  NOR _239_ (
    .A(_147_),
    .B(filled[1]),
    .Y(_032_)
  );
  NOR _240_ (
    .A(_030_),
    .B(_031_),
    .Y(_033_)
  );
  NOR _241_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _242_ (
    .A(_029_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _243_ (
    .A(umbralA[2]),
    .B(_022_),
    .Y(_036_)
  );
  NOR _244_ (
    .A(umbralA[2]),
    .B(_027_),
    .Y(_037_)
  );
  NOR _245_ (
    .A(umbralA[3]),
    .B(_037_),
    .Y(_038_)
  );
  NAND _246_ (
    .A(_036_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _247_ (
    .A(_035_),
    .B(_039_),
    .Y(almost_full)
  );
  NAND _248_ (
    .A(_146_),
    .B(filled[2]),
    .Y(_040_)
  );
  NAND _249_ (
    .A(umbralB[0]),
    .B(_152_),
    .Y(_041_)
  );
  NOT _250_ (
    .A(_041_),
    .Y(_042_)
  );
  NAND _251_ (
    .A(umbralB[1]),
    .B(_042_),
    .Y(_043_)
  );
  NAND _252_ (
    .A(_145_),
    .B(_041_),
    .Y(_044_)
  );
  NAND _253_ (
    .A(_161_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _254_ (
    .A(_043_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _255_ (
    .A(_040_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _256_ (
    .A(_146_),
    .B(filled[2]),
    .Y(_048_)
  );
  NOR _257_ (
    .A(umbralB[3]),
    .B(_048_),
    .Y(_049_)
  );
  NAND _258_ (
    .A(_047_),
    .B(_049_),
    .Y(almost_empty)
  );
  NAND _259_ (
    .A(push),
    .B(data_in[0]),
    .Y(_050_)
  );
  NOT _260_ (
    .A(_050_),
    .Y(to_fifo[0])
  );
  NAND _261_ (
    .A(push),
    .B(data_in[1]),
    .Y(_051_)
  );
  NOT _262_ (
    .A(_051_),
    .Y(to_fifo[1])
  );
  NAND _263_ (
    .A(push),
    .B(data_in[2]),
    .Y(_052_)
  );
  NOT _264_ (
    .A(_052_),
    .Y(to_fifo[2])
  );
  NAND _265_ (
    .A(push),
    .B(data_in[3]),
    .Y(_053_)
  );
  NOT _266_ (
    .A(_053_),
    .Y(to_fifo[3])
  );
  NAND _267_ (
    .A(push),
    .B(data_in[4]),
    .Y(_054_)
  );
  NOT _268_ (
    .A(_054_),
    .Y(to_fifo[4])
  );
  NAND _269_ (
    .A(wr_ptr[0]),
    .B(push),
    .Y(_055_)
  );
  NOR _270_ (
    .A(_136_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _271_ (
    .A(wr_ptr[2]),
    .B(_056_),
    .Y(_057_)
  );
  NOR _272_ (
    .A(_137_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _273_ (
    .A(valid_bus[7]),
    .B(_057_),
    .Y(_059_)
  );
  NOT _274_ (
    .A(_059_),
    .Y(_060_)
  );
  NOR _275_ (
    .A(_058_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _276_ (
    .A(reset),
    .B(_061_),
    .Y(_001_[7])
  );
  NAND _277_ (
    .A(wr_ptr[2]),
    .B(push),
    .Y(_062_)
  );
  NAND _278_ (
    .A(_134_),
    .B(wr_ptr[1]),
    .Y(_063_)
  );
  NOR _279_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _280_ (
    .A(valid_bus[6]),
    .B(_064_),
    .Y(_065_)
  );
  NAND _281_ (
    .A(_137_),
    .B(_064_),
    .Y(_066_)
  );
  NAND _282_ (
    .A(_138_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _283_ (
    .A(_065_),
    .B(_067_),
    .Y(_001_[6])
  );
  NAND _284_ (
    .A(wr_ptr[0]),
    .B(_136_),
    .Y(_068_)
  );
  NOR _285_ (
    .A(_062_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _286_ (
    .A(valid_bus[5]),
    .B(_069_),
    .Y(_070_)
  );
  NAND _287_ (
    .A(_137_),
    .B(_069_),
    .Y(_071_)
  );
  NAND _288_ (
    .A(_138_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _289_ (
    .A(_070_),
    .B(_072_),
    .Y(_001_[5])
  );
  NOR _290_ (
    .A(_163_),
    .B(_062_),
    .Y(_073_)
  );
  NOR _291_ (
    .A(valid_bus[4]),
    .B(_073_),
    .Y(_074_)
  );
  NAND _292_ (
    .A(_137_),
    .B(_073_),
    .Y(_075_)
  );
  NAND _293_ (
    .A(_138_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _294_ (
    .A(_074_),
    .B(_076_),
    .Y(_001_[4])
  );
  NAND _295_ (
    .A(_135_),
    .B(_056_),
    .Y(_077_)
  );
  NAND _296_ (
    .A(_140_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _297_ (
    .A(valid),
    .B(_077_),
    .Y(_079_)
  );
  NAND _298_ (
    .A(_138_),
    .B(_078_),
    .Y(_080_)
  );
  NOR _299_ (
    .A(_079_),
    .B(_080_),
    .Y(_001_[3])
  );
  NAND _300_ (
    .A(_135_),
    .B(push),
    .Y(_081_)
  );
  NOR _301_ (
    .A(_063_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _302_ (
    .A(valid_bus[2]),
    .B(_082_),
    .Y(_083_)
  );
  NAND _303_ (
    .A(_137_),
    .B(_082_),
    .Y(_084_)
  );
  NAND _304_ (
    .A(_138_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _305_ (
    .A(_083_),
    .B(_085_),
    .Y(_001_[2])
  );
  NOR _306_ (
    .A(_068_),
    .B(_081_),
    .Y(_086_)
  );
  NOR _307_ (
    .A(valid_bus[1]),
    .B(_086_),
    .Y(_087_)
  );
  NAND _308_ (
    .A(_137_),
    .B(_086_),
    .Y(_088_)
  );
  NAND _309_ (
    .A(_138_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _310_ (
    .A(_087_),
    .B(_089_),
    .Y(_001_[1])
  );
  NOR _311_ (
    .A(_163_),
    .B(_081_),
    .Y(_090_)
  );
  NOR _312_ (
    .A(valid_bus[0]),
    .B(_090_),
    .Y(_091_)
  );
  NAND _313_ (
    .A(_137_),
    .B(_090_),
    .Y(_092_)
  );
  NAND _314_ (
    .A(_138_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _315_ (
    .A(_091_),
    .B(_093_),
    .Y(_001_[0])
  );
  NAND _316_ (
    .A(valid_bus[7]),
    .B(rd_ptr[2]),
    .Y(_094_)
  );
  NAND _317_ (
    .A(valid_bus[3]),
    .B(_143_),
    .Y(_095_)
  );
  NAND _318_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  NAND _319_ (
    .A(rd_ptr[0]),
    .B(_096_),
    .Y(_097_)
  );
  NAND _320_ (
    .A(valid_bus[6]),
    .B(rd_ptr[2]),
    .Y(_098_)
  );
  NAND _321_ (
    .A(valid_bus[2]),
    .B(_143_),
    .Y(_099_)
  );
  NAND _322_ (
    .A(_098_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _323_ (
    .A(_144_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _324_ (
    .A(_097_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _325_ (
    .A(rd_ptr[1]),
    .B(_102_),
    .Y(_103_)
  );
  NOR _326_ (
    .A(_139_),
    .B(_143_),
    .Y(_104_)
  );
  NOR _327_ (
    .A(_141_),
    .B(rd_ptr[2]),
    .Y(_105_)
  );
  NOR _328_ (
    .A(_104_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _329_ (
    .A(_007_),
    .B(_106_),
    .Y(_107_)
  );
  NAND _330_ (
    .A(valid_bus[1]),
    .B(_143_),
    .Y(_108_)
  );
  NAND _331_ (
    .A(valid_bus[5]),
    .B(rd_ptr[2]),
    .Y(_109_)
  );
  NAND _332_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _333_ (
    .A(_165_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _334_ (
    .A(pop),
    .B(_111_),
    .Y(_112_)
  );
  NOR _335_ (
    .A(_107_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _336_ (
    .A(_103_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _337_ (
    .A(valid_out),
    .B(pop),
    .Y(_115_)
  );
  NAND _338_ (
    .A(_138_),
    .B(_114_),
    .Y(_116_)
  );
  NOR _339_ (
    .A(_115_),
    .B(_116_),
    .Y(_002_)
  );
  NOR _340_ (
    .A(wr_ptr[0]),
    .B(push),
    .Y(_117_)
  );
  NAND _341_ (
    .A(_138_),
    .B(_055_),
    .Y(_118_)
  );
  NOR _342_ (
    .A(_117_),
    .B(_118_),
    .Y(_003_[0])
  );
  NAND _343_ (
    .A(_136_),
    .B(_055_),
    .Y(_119_)
  );
  NAND _344_ (
    .A(_138_),
    .B(_119_),
    .Y(_120_)
  );
  NOR _345_ (
    .A(_056_),
    .B(_120_),
    .Y(_003_[1])
  );
  NOR _346_ (
    .A(wr_ptr[2]),
    .B(_056_),
    .Y(_121_)
  );
  NAND _347_ (
    .A(_138_),
    .B(_057_),
    .Y(_122_)
  );
  NOR _348_ (
    .A(_121_),
    .B(_122_),
    .Y(_003_[2])
  );
  NAND _349_ (
    .A(pop),
    .B(rd_ptr[0]),
    .Y(_123_)
  );
  NOR _350_ (
    .A(pop),
    .B(rd_ptr[0]),
    .Y(_124_)
  );
  NOR _351_ (
    .A(reset),
    .B(_124_),
    .Y(_125_)
  );
  NAND _352_ (
    .A(_123_),
    .B(_125_),
    .Y(_126_)
  );
  NOT _353_ (
    .A(_126_),
    .Y(_000_[0])
  );
  NOR _354_ (
    .A(_142_),
    .B(_123_),
    .Y(_127_)
  );
  NAND _355_ (
    .A(_142_),
    .B(_123_),
    .Y(_128_)
  );
  NAND _356_ (
    .A(_138_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _357_ (
    .A(_127_),
    .B(_129_),
    .Y(_000_[1])
  );
  NAND _358_ (
    .A(rd_ptr[2]),
    .B(_127_),
    .Y(_130_)
  );
  NOR _359_ (
    .A(rd_ptr[2]),
    .B(_127_),
    .Y(_131_)
  );
  NOR _360_ (
    .A(reset),
    .B(_131_),
    .Y(_132_)
  );
  NAND _361_ (
    .A(_130_),
    .B(_132_),
    .Y(_133_)
  );
  NOT _362_ (
    .A(_133_),
    .Y(_000_[2])
  );
  DFF _363_ (
    .C(clk),
    .D(_000_[0]),
    .Q(rd_ptr[0])
  );
  DFF _364_ (
    .C(clk),
    .D(_000_[1]),
    .Q(rd_ptr[1])
  );
  DFF _365_ (
    .C(clk),
    .D(_000_[2]),
    .Q(rd_ptr[2])
  );
  DFF _366_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  DFF _367_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
  DFF _368_ (
    .C(clk),
    .D(_003_[2]),
    .Q(wr_ptr[2])
  );
  DFF _369_ (
    .C(clk),
    .D(_002_),
    .Q(valid_out)
  );
  DFF _370_ (
    .C(clk),
    .D(_001_[0]),
    .Q(valid_bus[0])
  );
  DFF _371_ (
    .C(clk),
    .D(_001_[1]),
    .Q(valid_bus[1])
  );
  DFF _372_ (
    .C(clk),
    .D(_001_[2]),
    .Q(valid_bus[2])
  );
  DFF _373_ (
    .C(clk),
    .D(_001_[3]),
    .Q(valid_bus[3])
  );
  DFF _374_ (
    .C(clk),
    .D(_001_[4]),
    .Q(valid_bus[4])
  );
  DFF _375_ (
    .C(clk),
    .D(_001_[5]),
    .Q(valid_bus[5])
  );
  DFF _376_ (
    .C(clk),
    .D(_001_[6]),
    .Q(valid_bus[6])
  );
  DFF _377_ (
    .C(clk),
    .D(_001_[7]),
    .Q(valid_bus[7])
  );
  memoria_Synth channel (
    .addressR(rd_ptr),
    .addressW(wr_ptr),
    .clk(clk),
    .data_in(to_fifo),
    .data_out(data_out),
    .read(pop),
    .reset(reset),
    .write(push)
  );
  assign continua = almost_empty;
  assign filled[3] = 1'h0;
  assign pause = almost_full;
endmodule

module PCIE_Synth(clk, reset, valid_p0, valid_p1, data_p0, data_p1, umbralA, umbralB, init, out_p0, out_p1, pause_VC0P0, pause_VC1P0, pause_VC0P1, pause_VC1P1, continue_VC0P0, continue_VC1P0, continue_VC0P1, continue_VC1P1, umbrales_VCFC, active, idle, error);
  wire [4:0] _000_;
  wire [4:0] _001_;
  wire [4:0] _002_;
  wire [4:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire FIFO_empty;
  wire FIFO_error;
  output active;
  input clk;
  output continue_VC0P0;
  output continue_VC0P1;
  output continue_VC1P0;
  output continue_VC1P1;
  wire [4:0] data_VC0P0;
  wire [4:0] data_VC0P1;
  wire [4:0] data_VC1P0;
  wire [4:0] data_VC1P1;
  input [5:0] data_p0;
  input [5:0] data_p1;
  wire empty_VC0P0;
  wire empty_VC0P1;
  wire empty_VC1P0;
  wire empty_VC1P1;
  output error;
  wire fifoerr_VC0P0;
  wire fifoerr_VC0P1;
  wire fifoerr_VC1P0;
  wire fifoerr_VC1P1;
  output idle;
  input init;
  wire intermediate1;
  wire intermediate2;
  wire intermediate3;
  wire oValid_VC0P0;
  wire oValid_VC0P1;
  wire oValid_VC1P0;
  wire oValid_VC1P1;
  wire [4:0] ofifo_VC0P0;
  wire [4:0] ofifo_VC0P1;
  wire [4:0] ofifo_VC1P0;
  wire [4:0] ofifo_VC1P1;
  output [4:0] out_p0;
  output [4:0] out_p1;
  wire pause_V1CP0;
  wire pause_V1CP1;
  output pause_VC0P0;
  output pause_VC0P1;
  output pause_VC1P0;
  output pause_VC1P1;
  wire pop_VC0P0;
  wire pop_VC0P1;
  wire pop_VC1P0;
  wire pop_VC1P1;
  wire push_VC0P0;
  wire push_VC0P1;
  wire push_VC1P0;
  wire push_VC1P1;
  input reset;
  input [3:0] umbralA;
  input [3:0] umbralB;
  output [7:0] umbrales_VCFC;
  wire valid_VC0P0;
  wire valid_VC0P1;
  wire valid_VC1P0;
  wire valid_VC1P1;
  input valid_p0;
  input valid_p1;
  NOT _045_ (
    .A(pop_VC1P0),
    .Y(_018_)
  );
  NOT _046_ (
    .A(pop_VC0P1),
    .Y(_019_)
  );
  NOT _047_ (
    .A(pop_VC1P1),
    .Y(_020_)
  );
  NOT _048_ (
    .A(data_p0[0]),
    .Y(_021_)
  );
  NOT _049_ (
    .A(data_p0[5]),
    .Y(_022_)
  );
  NOT _050_ (
    .A(data_p0[1]),
    .Y(_023_)
  );
  NOT _051_ (
    .A(data_p0[2]),
    .Y(_024_)
  );
  NOT _052_ (
    .A(data_p0[3]),
    .Y(_025_)
  );
  NOT _053_ (
    .A(data_p0[4]),
    .Y(_026_)
  );
  NOT _054_ (
    .A(data_p1[0]),
    .Y(_027_)
  );
  NOT _055_ (
    .A(data_p1[5]),
    .Y(_028_)
  );
  NOT _056_ (
    .A(data_p1[1]),
    .Y(_029_)
  );
  NOT _057_ (
    .A(data_p1[2]),
    .Y(_030_)
  );
  NOT _058_ (
    .A(data_p1[3]),
    .Y(_031_)
  );
  NOT _059_ (
    .A(data_p1[4]),
    .Y(_032_)
  );
  NOT _060_ (
    .A(valid_p1),
    .Y(_033_)
  );
  NOT _061_ (
    .A(reset),
    .Y(_034_)
  );
  NOR _062_ (
    .A(empty_VC1P0),
    .B(_018_),
    .Y(intermediate3)
  );
  NOR _063_ (
    .A(empty_VC0P1),
    .B(_019_),
    .Y(intermediate1)
  );
  NOR _064_ (
    .A(empty_VC1P1),
    .B(_020_),
    .Y(intermediate2)
  );
  NOR _065_ (
    .A(fifoerr_VC0P0),
    .B(fifoerr_VC0P1),
    .Y(_035_)
  );
  NOR _066_ (
    .A(fifoerr_VC1P1),
    .B(fifoerr_VC1P0),
    .Y(_036_)
  );
  NAND _067_ (
    .A(_035_),
    .B(_036_),
    .Y(FIFO_error)
  );
  NAND _068_ (
    .A(empty_VC1P0),
    .B(empty_VC0P1),
    .Y(_037_)
  );
  NAND _069_ (
    .A(empty_VC1P1),
    .B(empty_VC0P0),
    .Y(_038_)
  );
  NOR _070_ (
    .A(_037_),
    .B(_038_),
    .Y(FIFO_empty)
  );
  NAND _071_ (
    .A(data_p1[5]),
    .B(_034_),
    .Y(_039_)
  );
  NOR _072_ (
    .A(_033_),
    .B(_039_),
    .Y(_009_)
  );
  NAND _073_ (
    .A(valid_p0),
    .B(_034_),
    .Y(_040_)
  );
  NOR _074_ (
    .A(data_p0[5]),
    .B(_040_),
    .Y(_008_)
  );
  NOR _075_ (
    .A(_027_),
    .B(_039_),
    .Y(_003_[0])
  );
  NOR _076_ (
    .A(_029_),
    .B(_039_),
    .Y(_003_[1])
  );
  NOR _077_ (
    .A(_030_),
    .B(_039_),
    .Y(_003_[2])
  );
  NOR _078_ (
    .A(_031_),
    .B(_039_),
    .Y(_003_[3])
  );
  NOR _079_ (
    .A(_032_),
    .B(_039_),
    .Y(_003_[4])
  );
  NAND _080_ (
    .A(_028_),
    .B(valid_p1),
    .Y(_041_)
  );
  NOR _081_ (
    .A(reset),
    .B(_041_),
    .Y(_005_)
  );
  NAND _082_ (
    .A(data_p1[0]),
    .B(_028_),
    .Y(_042_)
  );
  NOR _083_ (
    .A(reset),
    .B(_042_),
    .Y(_001_[0])
  );
  NAND _084_ (
    .A(_028_),
    .B(data_p1[1]),
    .Y(_043_)
  );
  NOR _085_ (
    .A(reset),
    .B(_043_),
    .Y(_001_[1])
  );
  NAND _086_ (
    .A(_028_),
    .B(data_p1[2]),
    .Y(_044_)
  );
  NOR _087_ (
    .A(reset),
    .B(_044_),
    .Y(_001_[2])
  );
  NAND _088_ (
    .A(_028_),
    .B(data_p1[3]),
    .Y(_010_)
  );
  NOR _089_ (
    .A(reset),
    .B(_010_),
    .Y(_001_[3])
  );
  NAND _090_ (
    .A(_028_),
    .B(data_p1[4]),
    .Y(_011_)
  );
  NOR _091_ (
    .A(reset),
    .B(_011_),
    .Y(_001_[4])
  );
  NAND _092_ (
    .A(data_p0[5]),
    .B(_034_),
    .Y(_012_)
  );
  NOR _093_ (
    .A(_022_),
    .B(_040_),
    .Y(_006_)
  );
  NOR _094_ (
    .A(_021_),
    .B(_012_),
    .Y(_002_[0])
  );
  NOR _095_ (
    .A(_023_),
    .B(_012_),
    .Y(_002_[1])
  );
  NOR _096_ (
    .A(_024_),
    .B(_012_),
    .Y(_002_[2])
  );
  NOR _097_ (
    .A(_025_),
    .B(_012_),
    .Y(_002_[3])
  );
  NOR _098_ (
    .A(_026_),
    .B(_012_),
    .Y(_002_[4])
  );
  NAND _099_ (
    .A(data_p0[0]),
    .B(_022_),
    .Y(_013_)
  );
  NOR _100_ (
    .A(reset),
    .B(_013_),
    .Y(_000_[0])
  );
  NAND _101_ (
    .A(_022_),
    .B(data_p0[1]),
    .Y(_014_)
  );
  NOR _102_ (
    .A(reset),
    .B(_014_),
    .Y(_000_[1])
  );
  NAND _103_ (
    .A(_022_),
    .B(data_p0[2]),
    .Y(_015_)
  );
  NOR _104_ (
    .A(reset),
    .B(_015_),
    .Y(_000_[2])
  );
  NAND _105_ (
    .A(_022_),
    .B(data_p0[3]),
    .Y(_016_)
  );
  NOR _106_ (
    .A(reset),
    .B(_016_),
    .Y(_000_[3])
  );
  NAND _107_ (
    .A(_022_),
    .B(data_p0[4]),
    .Y(_017_)
  );
  NOR _108_ (
    .A(reset),
    .B(_017_),
    .Y(_000_[4])
  );
  NOR _109_ (
    .A(_033_),
    .B(_039_),
    .Y(_007_)
  );
  NOR _110_ (
    .A(data_p0[5]),
    .B(_040_),
    .Y(_004_)
  );
  DFF _111_ (
    .C(clk),
    .D(_008_),
    .Q(valid_VC0P1)
  );
  DFF _112_ (
    .C(clk),
    .D(_009_),
    .Q(valid_VC1P1)
  );
  DFF _113_ (
    .C(clk),
    .D(_004_),
    .Q(push_VC0P0)
  );
  DFF _114_ (
    .C(clk),
    .D(_006_),
    .Q(push_VC1P0)
  );
  DFF _115_ (
    .C(clk),
    .D(_005_),
    .Q(push_VC0P1)
  );
  DFF _116_ (
    .C(clk),
    .D(_007_),
    .Q(push_VC1P1)
  );
  DFF _117_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_VC0P0[0])
  );
  DFF _118_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_VC0P0[1])
  );
  DFF _119_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_VC0P0[2])
  );
  DFF _120_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_VC0P0[3])
  );
  DFF _121_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_VC0P0[4])
  );
  DFF _122_ (
    .C(clk),
    .D(_002_[0]),
    .Q(data_VC1P0[0])
  );
  DFF _123_ (
    .C(clk),
    .D(_002_[1]),
    .Q(data_VC1P0[1])
  );
  DFF _124_ (
    .C(clk),
    .D(_002_[2]),
    .Q(data_VC1P0[2])
  );
  DFF _125_ (
    .C(clk),
    .D(_002_[3]),
    .Q(data_VC1P0[3])
  );
  DFF _126_ (
    .C(clk),
    .D(_002_[4]),
    .Q(data_VC1P0[4])
  );
  DFF _127_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_VC0P1[0])
  );
  DFF _128_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_VC0P1[1])
  );
  DFF _129_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_VC0P1[2])
  );
  DFF _130_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_VC0P1[3])
  );
  DFF _131_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_VC0P1[4])
  );
  DFF _132_ (
    .C(clk),
    .D(_003_[0]),
    .Q(data_VC1P1[0])
  );
  DFF _133_ (
    .C(clk),
    .D(_003_[1]),
    .Q(data_VC1P1[1])
  );
  DFF _134_ (
    .C(clk),
    .D(_003_[2]),
    .Q(data_VC1P1[2])
  );
  DFF _135_ (
    .C(clk),
    .D(_003_[3]),
    .Q(data_VC1P1[3])
  );
  DFF _136_ (
    .C(clk),
    .D(_003_[4]),
    .Q(data_VC1P1[4])
  );
  arbitroSynth arbitro1 (
    .VC0_p0(ofifo_VC0P0),
    .VC0_p1(ofifo_VC0P1),
    .VC1_p0(ofifo_VC1P0),
    .VC1_p1(ofifo_VC1P1),
    .clk(clk),
    .dataOut_0(out_p0),
    .dataOut_1(out_p1),
    .emptyVC0_p0(empty_VC0P0),
    .emptyVC0_p1(empty_VC0P1),
    .emptyVC1_p0(empty_VC1P0),
    .emptyVC1_p1(empty_VC1P1),
    .popVC0_0(pop_VC0P0),
    .popVC0_1(pop_VC0P1),
    .popVC1_0(pop_VC1P0),
    .popVC1_1(pop_VC1P1),
    .reset_L(reset),
    .validBits({ oValid_VC0P0, oValid_VC1P0, oValid_VC0P1, oValid_VC1P1 })
  );
  FIFOSynth fifo_VC0P0 (
    .clk(clk),
    .continua(continue_VC0P0),
    .data_in(data_VC0P0),
    .data_out(ofifo_VC0P0),
    .empty(empty_VC0P0),
    .fifo_error(fifoerr_VC0P0),
    .pause(pause_VC0P0),
    .pop(pop_VC0P0),
    .push(push_VC0P0),
    .reset(reset),
    .umbralA(umbrales_VCFC[7:4]),
    .umbralB(umbrales_VCFC[3:0]),
    .valid(valid_VC0P1),
    .valid_out(oValid_VC0P0)
  );
  FIFOSynth fifo_VC0P1 (
    .clk(clk),
    .continua(continue_VC0P1),
    .data_in(data_VC0P1),
    .data_out(ofifo_VC0P1),
    .empty(empty_VC0P1),
    .fifo_error(fifoerr_VC0P1),
    .pause(pause_VC0P1),
    .pop(intermediate1),
    .push(push_VC0P1),
    .reset(reset),
    .umbralA(umbrales_VCFC[7:4]),
    .umbralB(umbrales_VCFC[3:0]),
    .valid(valid_VC0P1),
    .valid_out(oValid_VC0P1)
  );
  FIFOSynth fifo_VC1P0 (
    .clk(clk),
    .continua(continue_VC1P0),
    .data_in(data_VC1P0),
    .data_out(ofifo_VC1P0),
    .empty(empty_VC1P0),
    .fifo_error(fifoerr_VC1P0),
    .pause(pause_V1CP0),
    .pop(intermediate3),
    .push(push_VC1P0),
    .reset(reset),
    .umbralA(umbrales_VCFC[7:4]),
    .umbralB(umbrales_VCFC[3:0]),
    .valid(valid_VC1P1),
    .valid_out(oValid_VC1P0)
  );
  FIFOSynth fifo_VC1P1 (
    .clk(clk),
    .continua(continue_VC1P1),
    .data_in(data_VC1P1),
    .data_out(ofifo_VC1P1),
    .empty(empty_VC1P1),
    .fifo_error(fifoerr_VC1P1),
    .pause(pause_V1CP1),
    .pop(intermediate2),
    .push(push_VC1P1),
    .reset(reset),
    .umbralA(umbrales_VCFC[7:4]),
    .umbralB(umbrales_VCFC[3:0]),
    .valid(valid_VC1P1),
    .valid_out(oValid_VC1P1)
  );
  fsmControlSynth fsm (
    .FIFO_empty(FIFO_empty),
    .FIFO_error(FIFO_error),
    .active(active),
    .clk(clk),
    .error(error),
    .idle(idle),
    .init(init),
    .reset_L(reset),
    .umbral_VCFC({ umbralA, umbralB }),
    .umbrales_VCFC(umbrales_VCFC)
  );
  assign valid_VC0P0 = valid_VC0P1;
  assign valid_VC1P0 = valid_VC1P1;
endmodule

module arbitroSynth(clk, reset_L, VC0_p0, VC1_p0, VC0_p1, VC1_p1, validBits, emptyVC0_p0, emptyVC1_p0, emptyVC0_p1, emptyVC1_p1, popVC0_0, popVC1_0, popVC0_1, popVC1_1, dataOut_0, dataOut_1, validBitsOut);
  wire [4:0] _000_;
  wire [4:0] _001_;
  wire [5:0] _002_;
  wire [4:0] _003_;
  wire [4:0] _004_;
  wire [1:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  input [4:0] VC0_p0;
  input [4:0] VC0_p1;
  input [4:0] VC1_p0;
  input [4:0] VC1_p1;
  input clk;
  output [4:0] dataOut_0;
  output [4:0] dataOut_1;
  input emptyVC0_p0;
  input emptyVC0_p1;
  input emptyVC1_p0;
  input emptyVC1_p1;
  wire [5:0] muxMultiOut;
  wire [4:0] muxVC0_muxMulti;
  wire [4:0] muxVC1_muxMulti;
  output popVC0_0;
  output popVC0_1;
  output popVC1_0;
  output popVC1_1;
  wire request0_VC0;
  wire request0_VC1;
  wire request1_VC0;
  wire request1_VC1;
  input reset_L;
  wire selectMUX_VC0;
  wire selectMUX_VC1;
  input [3:0] validBits;
  output [1:0] validBitsOut;
  wire validMuxVC0;
  wire validMuxVC1;
  wire validMux_VC0;
  wire validMux_VC1;
  NOT _127_ (
    .A(VC0_p1[0]),
    .Y(_124_)
  );
  NOT _128_ (
    .A(VC0_p1[1]),
    .Y(_125_)
  );
  NOT _129_ (
    .A(VC0_p1[2]),
    .Y(_126_)
  );
  NOT _130_ (
    .A(VC0_p1[3]),
    .Y(_008_)
  );
  NOT _131_ (
    .A(VC0_p1[4]),
    .Y(_009_)
  );
  NOT _132_ (
    .A(validBits[1]),
    .Y(_010_)
  );
  NOT _133_ (
    .A(VC1_p1[0]),
    .Y(_011_)
  );
  NOT _134_ (
    .A(VC1_p1[1]),
    .Y(_012_)
  );
  NOT _135_ (
    .A(VC1_p1[2]),
    .Y(_013_)
  );
  NOT _136_ (
    .A(VC1_p1[3]),
    .Y(_014_)
  );
  NOT _137_ (
    .A(VC1_p1[4]),
    .Y(_015_)
  );
  NOT _138_ (
    .A(validBits[3]),
    .Y(_016_)
  );
  NOT _139_ (
    .A(muxVC1_muxMulti[0]),
    .Y(_017_)
  );
  NOT _140_ (
    .A(validMux_VC0),
    .Y(_018_)
  );
  NOT _141_ (
    .A(muxVC1_muxMulti[1]),
    .Y(_019_)
  );
  NOT _142_ (
    .A(muxVC1_muxMulti[2]),
    .Y(_020_)
  );
  NOT _143_ (
    .A(muxVC1_muxMulti[3]),
    .Y(_021_)
  );
  NOT _144_ (
    .A(muxVC1_muxMulti[4]),
    .Y(_022_)
  );
  NOT _145_ (
    .A(validMuxVC1),
    .Y(_023_)
  );
  NOT _146_ (
    .A(reset_L),
    .Y(_024_)
  );
  NOT _147_ (
    .A(validBitsOut[0]),
    .Y(_025_)
  );
  NOT _148_ (
    .A(muxMultiOut[0]),
    .Y(_026_)
  );
  NOT _149_ (
    .A(muxMultiOut[1]),
    .Y(_027_)
  );
  NOT _150_ (
    .A(muxMultiOut[2]),
    .Y(_028_)
  );
  NOT _151_ (
    .A(muxMultiOut[3]),
    .Y(_029_)
  );
  NOT _152_ (
    .A(muxMultiOut[5]),
    .Y(_030_)
  );
  NOT _153_ (
    .A(emptyVC0_p0),
    .Y(request0_VC0)
  );
  NOT _154_ (
    .A(emptyVC0_p1),
    .Y(request1_VC0)
  );
  NOR _155_ (
    .A(validBitsOut[1]),
    .B(muxMultiOut[4]),
    .Y(_031_)
  );
  NAND _156_ (
    .A(_023_),
    .B(muxMultiOut[4]),
    .Y(_032_)
  );
  NAND _157_ (
    .A(_024_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _158_ (
    .A(_031_),
    .B(_033_),
    .Y(_005_[1])
  );
  NOR _159_ (
    .A(muxMultiOut[4]),
    .B(validMuxVC0),
    .Y(_034_)
  );
  NAND _160_ (
    .A(muxMultiOut[4]),
    .B(_025_),
    .Y(_035_)
  );
  NAND _161_ (
    .A(_024_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _162_ (
    .A(_034_),
    .B(_036_),
    .Y(_005_[0])
  );
  NOR _163_ (
    .A(selectMUX_VC1),
    .B(validBits[2]),
    .Y(_037_)
  );
  NAND _164_ (
    .A(selectMUX_VC1),
    .B(_016_),
    .Y(_038_)
  );
  NAND _165_ (
    .A(_024_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _166_ (
    .A(_037_),
    .B(_039_),
    .Y(_007_)
  );
  NOR _167_ (
    .A(selectMUX_VC0),
    .B(validBits[0]),
    .Y(_040_)
  );
  NAND _168_ (
    .A(selectMUX_VC0),
    .B(_010_),
    .Y(_041_)
  );
  NAND _169_ (
    .A(_024_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _170_ (
    .A(_040_),
    .B(_042_),
    .Y(_006_)
  );
  NAND _171_ (
    .A(_017_),
    .B(validMux_VC0),
    .Y(_043_)
  );
  NAND _172_ (
    .A(_024_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _173_ (
    .A(muxVC0_muxMulti[0]),
    .B(validMux_VC0),
    .Y(_045_)
  );
  NOR _174_ (
    .A(_044_),
    .B(_045_),
    .Y(_002_[0])
  );
  NAND _175_ (
    .A(validMux_VC0),
    .B(_019_),
    .Y(_046_)
  );
  NAND _176_ (
    .A(_024_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _177_ (
    .A(validMux_VC0),
    .B(muxVC0_muxMulti[1]),
    .Y(_048_)
  );
  NOR _178_ (
    .A(_047_),
    .B(_048_),
    .Y(_002_[1])
  );
  NAND _179_ (
    .A(validMux_VC0),
    .B(_020_),
    .Y(_049_)
  );
  NAND _180_ (
    .A(_024_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _181_ (
    .A(validMux_VC0),
    .B(muxVC0_muxMulti[2]),
    .Y(_051_)
  );
  NOR _182_ (
    .A(_050_),
    .B(_051_),
    .Y(_002_[2])
  );
  NAND _183_ (
    .A(validMux_VC0),
    .B(_021_),
    .Y(_052_)
  );
  NAND _184_ (
    .A(_024_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _185_ (
    .A(validMux_VC0),
    .B(muxVC0_muxMulti[3]),
    .Y(_054_)
  );
  NOR _186_ (
    .A(_053_),
    .B(_054_),
    .Y(_002_[3])
  );
  NAND _187_ (
    .A(validMux_VC0),
    .B(_022_),
    .Y(_055_)
  );
  NAND _188_ (
    .A(_024_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _189_ (
    .A(validMux_VC0),
    .B(muxVC0_muxMulti[4]),
    .Y(_057_)
  );
  NOR _190_ (
    .A(_056_),
    .B(_057_),
    .Y(_002_[4])
  );
  NOR _191_ (
    .A(_018_),
    .B(reset_L),
    .Y(_002_[5])
  );
  NOR _192_ (
    .A(VC1_p0[0]),
    .B(selectMUX_VC1),
    .Y(_058_)
  );
  NAND _193_ (
    .A(_011_),
    .B(selectMUX_VC1),
    .Y(_059_)
  );
  NAND _194_ (
    .A(_024_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _195_ (
    .A(_058_),
    .B(_060_),
    .Y(_004_[0])
  );
  NOR _196_ (
    .A(selectMUX_VC1),
    .B(VC1_p0[1]),
    .Y(_061_)
  );
  NAND _197_ (
    .A(selectMUX_VC1),
    .B(_012_),
    .Y(_062_)
  );
  NAND _198_ (
    .A(_024_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _199_ (
    .A(_061_),
    .B(_063_),
    .Y(_004_[1])
  );
  NOR _200_ (
    .A(selectMUX_VC1),
    .B(VC1_p0[2]),
    .Y(_064_)
  );
  NAND _201_ (
    .A(selectMUX_VC1),
    .B(_013_),
    .Y(_065_)
  );
  NAND _202_ (
    .A(_024_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _203_ (
    .A(_064_),
    .B(_066_),
    .Y(_004_[2])
  );
  NOR _204_ (
    .A(selectMUX_VC1),
    .B(VC1_p0[3]),
    .Y(_067_)
  );
  NAND _205_ (
    .A(selectMUX_VC1),
    .B(_014_),
    .Y(_068_)
  );
  NAND _206_ (
    .A(_024_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _207_ (
    .A(_067_),
    .B(_069_),
    .Y(_004_[3])
  );
  NOR _208_ (
    .A(selectMUX_VC1),
    .B(VC1_p0[4]),
    .Y(_070_)
  );
  NAND _209_ (
    .A(selectMUX_VC1),
    .B(_015_),
    .Y(_071_)
  );
  NAND _210_ (
    .A(_024_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _211_ (
    .A(_070_),
    .B(_072_),
    .Y(_004_[4])
  );
  NOR _212_ (
    .A(VC0_p0[0]),
    .B(selectMUX_VC0),
    .Y(_073_)
  );
  NAND _213_ (
    .A(_124_),
    .B(selectMUX_VC0),
    .Y(_074_)
  );
  NAND _214_ (
    .A(_024_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _215_ (
    .A(_073_),
    .B(_075_),
    .Y(_003_[0])
  );
  NOR _216_ (
    .A(selectMUX_VC0),
    .B(VC0_p0[1]),
    .Y(_076_)
  );
  NAND _217_ (
    .A(selectMUX_VC0),
    .B(_125_),
    .Y(_077_)
  );
  NAND _218_ (
    .A(_024_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _219_ (
    .A(_076_),
    .B(_078_),
    .Y(_003_[1])
  );
  NOR _220_ (
    .A(selectMUX_VC0),
    .B(VC0_p0[2]),
    .Y(_079_)
  );
  NAND _221_ (
    .A(selectMUX_VC0),
    .B(_126_),
    .Y(_080_)
  );
  NAND _222_ (
    .A(_024_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _223_ (
    .A(_079_),
    .B(_081_),
    .Y(_003_[2])
  );
  NOR _224_ (
    .A(selectMUX_VC0),
    .B(VC0_p0[3]),
    .Y(_082_)
  );
  NAND _225_ (
    .A(selectMUX_VC0),
    .B(_008_),
    .Y(_083_)
  );
  NAND _226_ (
    .A(_024_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _227_ (
    .A(_082_),
    .B(_084_),
    .Y(_003_[3])
  );
  NOR _228_ (
    .A(selectMUX_VC0),
    .B(VC0_p0[4]),
    .Y(_085_)
  );
  NAND _229_ (
    .A(selectMUX_VC0),
    .B(_009_),
    .Y(_086_)
  );
  NAND _230_ (
    .A(_024_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _231_ (
    .A(_085_),
    .B(_087_),
    .Y(_003_[4])
  );
  NOR _232_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[0]),
    .Y(_088_)
  );
  NAND _233_ (
    .A(muxMultiOut[4]),
    .B(_026_),
    .Y(_089_)
  );
  NAND _234_ (
    .A(_024_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _235_ (
    .A(_088_),
    .B(_090_),
    .Y(_001_[0])
  );
  NOR _236_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[1]),
    .Y(_091_)
  );
  NAND _237_ (
    .A(muxMultiOut[4]),
    .B(_027_),
    .Y(_092_)
  );
  NAND _238_ (
    .A(_024_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _239_ (
    .A(_091_),
    .B(_093_),
    .Y(_001_[1])
  );
  NOR _240_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[2]),
    .Y(_094_)
  );
  NAND _241_ (
    .A(muxMultiOut[4]),
    .B(_028_),
    .Y(_095_)
  );
  NAND _242_ (
    .A(_024_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _243_ (
    .A(_094_),
    .B(_096_),
    .Y(_001_[2])
  );
  NOR _244_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[3]),
    .Y(_097_)
  );
  NAND _245_ (
    .A(muxMultiOut[4]),
    .B(_029_),
    .Y(_098_)
  );
  NAND _246_ (
    .A(_024_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _247_ (
    .A(_097_),
    .B(_099_),
    .Y(_001_[3])
  );
  NOR _248_ (
    .A(muxMultiOut[4]),
    .B(dataOut_1[4]),
    .Y(_100_)
  );
  NAND _249_ (
    .A(muxMultiOut[4]),
    .B(_030_),
    .Y(_101_)
  );
  NAND _250_ (
    .A(_024_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _251_ (
    .A(_100_),
    .B(_102_),
    .Y(_001_[4])
  );
  NAND _252_ (
    .A(muxMultiOut[4]),
    .B(dataOut_0[0]),
    .Y(_103_)
  );
  NOT _253_ (
    .A(_103_),
    .Y(_104_)
  );
  NOR _254_ (
    .A(muxMultiOut[4]),
    .B(_026_),
    .Y(_105_)
  );
  NOR _255_ (
    .A(_104_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _256_ (
    .A(reset_L),
    .B(_106_),
    .Y(_000_[0])
  );
  NAND _257_ (
    .A(muxMultiOut[4]),
    .B(dataOut_0[1]),
    .Y(_107_)
  );
  NOT _258_ (
    .A(_107_),
    .Y(_108_)
  );
  NOR _259_ (
    .A(muxMultiOut[4]),
    .B(_027_),
    .Y(_109_)
  );
  NOR _260_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  NOR _261_ (
    .A(reset_L),
    .B(_110_),
    .Y(_000_[1])
  );
  NAND _262_ (
    .A(muxMultiOut[4]),
    .B(dataOut_0[2]),
    .Y(_111_)
  );
  NOT _263_ (
    .A(_111_),
    .Y(_112_)
  );
  NOR _264_ (
    .A(muxMultiOut[4]),
    .B(_028_),
    .Y(_113_)
  );
  NOR _265_ (
    .A(_112_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _266_ (
    .A(reset_L),
    .B(_114_),
    .Y(_000_[2])
  );
  NAND _267_ (
    .A(muxMultiOut[4]),
    .B(dataOut_0[3]),
    .Y(_115_)
  );
  NOT _268_ (
    .A(_115_),
    .Y(_116_)
  );
  NOR _269_ (
    .A(muxMultiOut[4]),
    .B(_029_),
    .Y(_117_)
  );
  NOR _270_ (
    .A(_116_),
    .B(_117_),
    .Y(_118_)
  );
  NOR _271_ (
    .A(reset_L),
    .B(_118_),
    .Y(_000_[3])
  );
  NAND _272_ (
    .A(muxMultiOut[4]),
    .B(dataOut_0[4]),
    .Y(_119_)
  );
  NOT _273_ (
    .A(_119_),
    .Y(_120_)
  );
  NOR _274_ (
    .A(muxMultiOut[4]),
    .B(_030_),
    .Y(_121_)
  );
  NOR _275_ (
    .A(_120_),
    .B(_121_),
    .Y(_122_)
  );
  NOR _276_ (
    .A(reset_L),
    .B(_122_),
    .Y(_000_[4])
  );
  NAND _277_ (
    .A(emptyVC0_p0),
    .B(emptyVC0_p1),
    .Y(_123_)
  );
  NOR _278_ (
    .A(emptyVC1_p0),
    .B(_123_),
    .Y(request0_VC1)
  );
  NOR _279_ (
    .A(emptyVC1_p1),
    .B(_123_),
    .Y(request1_VC1)
  );
  DFF _280_ (
    .C(clk),
    .D(_000_[0]),
    .Q(dataOut_0[0])
  );
  DFF _281_ (
    .C(clk),
    .D(_000_[1]),
    .Q(dataOut_0[1])
  );
  DFF _282_ (
    .C(clk),
    .D(_000_[2]),
    .Q(dataOut_0[2])
  );
  DFF _283_ (
    .C(clk),
    .D(_000_[3]),
    .Q(dataOut_0[3])
  );
  DFF _284_ (
    .C(clk),
    .D(_000_[4]),
    .Q(dataOut_0[4])
  );
  DFF _285_ (
    .C(clk),
    .D(_001_[0]),
    .Q(dataOut_1[0])
  );
  DFF _286_ (
    .C(clk),
    .D(_001_[1]),
    .Q(dataOut_1[1])
  );
  DFF _287_ (
    .C(clk),
    .D(_001_[2]),
    .Q(dataOut_1[2])
  );
  DFF _288_ (
    .C(clk),
    .D(_001_[3]),
    .Q(dataOut_1[3])
  );
  DFF _289_ (
    .C(clk),
    .D(_001_[4]),
    .Q(dataOut_1[4])
  );
  DFF _290_ (
    .C(clk),
    .D(_005_[0]),
    .Q(validBitsOut[0])
  );
  DFF _291_ (
    .C(clk),
    .D(_005_[1]),
    .Q(validBitsOut[1])
  );
  DFF _292_ (
    .C(clk),
    .D(_003_[0]),
    .Q(muxVC0_muxMulti[0])
  );
  DFF _293_ (
    .C(clk),
    .D(_003_[1]),
    .Q(muxVC0_muxMulti[1])
  );
  DFF _294_ (
    .C(clk),
    .D(_003_[2]),
    .Q(muxVC0_muxMulti[2])
  );
  DFF _295_ (
    .C(clk),
    .D(_003_[3]),
    .Q(muxVC0_muxMulti[3])
  );
  DFF _296_ (
    .C(clk),
    .D(_003_[4]),
    .Q(muxVC0_muxMulti[4])
  );
  DFF _297_ (
    .C(clk),
    .D(_004_[0]),
    .Q(muxVC1_muxMulti[0])
  );
  DFF _298_ (
    .C(clk),
    .D(_004_[1]),
    .Q(muxVC1_muxMulti[1])
  );
  DFF _299_ (
    .C(clk),
    .D(_004_[2]),
    .Q(muxVC1_muxMulti[2])
  );
  DFF _300_ (
    .C(clk),
    .D(_004_[3]),
    .Q(muxVC1_muxMulti[3])
  );
  DFF _301_ (
    .C(clk),
    .D(_004_[4]),
    .Q(muxVC1_muxMulti[4])
  );
  DFF _302_ (
    .C(clk),
    .D(_002_[0]),
    .Q(muxMultiOut[0])
  );
  DFF _303_ (
    .C(clk),
    .D(_002_[1]),
    .Q(muxMultiOut[1])
  );
  DFF _304_ (
    .C(clk),
    .D(_002_[2]),
    .Q(muxMultiOut[2])
  );
  DFF _305_ (
    .C(clk),
    .D(_002_[3]),
    .Q(muxMultiOut[3])
  );
  DFF _306_ (
    .C(clk),
    .D(_002_[4]),
    .Q(muxMultiOut[4])
  );
  DFF _307_ (
    .C(clk),
    .D(_002_[5]),
    .Q(muxMultiOut[5])
  );
  DFF _308_ (
    .C(clk),
    .D(_006_),
    .Q(validMuxVC0)
  );
  DFF _309_ (
    .C(clk),
    .D(_007_),
    .Q(validMuxVC1)
  );
  roundRobin_Synth roundRobinVC0 (
    .clk(clk),
    .pop_0(popVC0_0),
    .pop_1(popVC0_1),
    .portMux(selectMUX_VC0),
    .request0(request0_VC0),
    .request1(request1_VC0),
    .reset_L(reset_L),
    .validMux(validMux_VC0)
  );
  roundRobin_Synth roundRobinVC1 (
    .clk(clk),
    .pop_0(popVC1_0),
    .pop_1(popVC1_1),
    .portMux(selectMUX_VC1),
    .request0(request0_VC1),
    .request1(request1_VC1),
    .reset_L(reset_L),
    .validMux(validMux_VC1)
  );
endmodule

module fsmControlSynth(clk, reset_L, init, umbral_VCFC, FIFO_error, FIFO_empty, umbrales_VCFC, active, idle, error);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  input FIFO_empty;
  input FIFO_error;
  output active;
  input clk;
  output error;
  output idle;
  input init;
  input reset_L;
  wire [4:0] state;
  input [7:0] umbral_VCFC;
  output [7:0] umbrales_VCFC;
  NOT _31_ (
    .A(state[3]),
    .Y(_04_)
  );
  NOT _32_ (
    .A(state[2]),
    .Y(_05_)
  );
  NOT _33_ (
    .A(reset_L),
    .Y(_06_)
  );
  NOT _34_ (
    .A(init),
    .Y(_07_)
  );
  NOT _35_ (
    .A(FIFO_error),
    .Y(_08_)
  );
  NOT _36_ (
    .A(umbral_VCFC[0]),
    .Y(_09_)
  );
  NOT _37_ (
    .A(umbral_VCFC[1]),
    .Y(_10_)
  );
  NOT _38_ (
    .A(umbral_VCFC[2]),
    .Y(_11_)
  );
  NOT _39_ (
    .A(umbral_VCFC[3]),
    .Y(_12_)
  );
  NOT _40_ (
    .A(umbral_VCFC[4]),
    .Y(_13_)
  );
  NOT _41_ (
    .A(umbral_VCFC[5]),
    .Y(_14_)
  );
  NOT _42_ (
    .A(umbral_VCFC[6]),
    .Y(_15_)
  );
  NOT _43_ (
    .A(umbral_VCFC[7]),
    .Y(_16_)
  );
  NAND _44_ (
    .A(_06_),
    .B(_08_),
    .Y(_17_)
  );
  NOR _45_ (
    .A(_04_),
    .B(FIFO_empty),
    .Y(_18_)
  );
  NOR _46_ (
    .A(state[2]),
    .B(_18_),
    .Y(_19_)
  );
  NOR _47_ (
    .A(_17_),
    .B(_19_),
    .Y(_00_)
  );
  NOR _48_ (
    .A(state[4]),
    .B(state[3]),
    .Y(_20_)
  );
  NOT _49_ (
    .A(_20_),
    .Y(_21_)
  );
  NOR _50_ (
    .A(state[2]),
    .B(_21_),
    .Y(_22_)
  );
  NOR _51_ (
    .A(_08_),
    .B(_22_),
    .Y(_23_)
  );
  NOR _52_ (
    .A(state[1]),
    .B(_23_),
    .Y(_24_)
  );
  NOR _53_ (
    .A(reset_L),
    .B(_24_),
    .Y(_01_)
  );
  NAND _54_ (
    .A(_07_),
    .B(state[0]),
    .Y(_25_)
  );
  NAND _55_ (
    .A(_06_),
    .B(_25_),
    .Y(_02_)
  );
  NAND _56_ (
    .A(state[3]),
    .B(FIFO_empty),
    .Y(_26_)
  );
  NOT _57_ (
    .A(_26_),
    .Y(_28_)
  );
  NOR _58_ (
    .A(state[4]),
    .B(_28_),
    .Y(_29_)
  );
  NOR _59_ (
    .A(_17_),
    .B(_29_),
    .Y(_03_)
  );
  NOR _60_ (
    .A(FIFO_error),
    .B(_26_),
    .Y(idle)
  );
  NOR _61_ (
    .A(_05_),
    .B(FIFO_error),
    .Y(active)
  );
  NOR _62_ (
    .A(_09_),
    .B(_22_),
    .Y(umbrales_VCFC[0])
  );
  NOR _63_ (
    .A(_10_),
    .B(_22_),
    .Y(umbrales_VCFC[1])
  );
  NOR _64_ (
    .A(_11_),
    .B(_22_),
    .Y(umbrales_VCFC[2])
  );
  NOR _65_ (
    .A(_12_),
    .B(_22_),
    .Y(umbrales_VCFC[3])
  );
  NOR _66_ (
    .A(_13_),
    .B(_22_),
    .Y(umbrales_VCFC[4])
  );
  NOR _67_ (
    .A(_14_),
    .B(_22_),
    .Y(umbrales_VCFC[5])
  );
  NOR _68_ (
    .A(_15_),
    .B(_22_),
    .Y(umbrales_VCFC[6])
  );
  NOR _69_ (
    .A(_16_),
    .B(_22_),
    .Y(umbrales_VCFC[7])
  );
  NAND _70_ (
    .A(init),
    .B(state[0]),
    .Y(_30_)
  );
  NOR _71_ (
    .A(reset_L),
    .B(_30_),
    .Y(_27_)
  );
  DFF _72_ (
    .C(clk),
    .D(_02_),
    .Q(state[0])
  );
  DFF _73_ (
    .C(clk),
    .D(_01_),
    .Q(state[1])
  );
  DFF _74_ (
    .C(clk),
    .D(_00_),
    .Q(state[2])
  );
  DFF _75_ (
    .C(clk),
    .D(_03_),
    .Q(state[3])
  );
  DFF _76_ (
    .C(clk),
    .D(_27_),
    .Q(state[4])
  );
  assign error = state[1];
endmodule

module memoria_Synth(clk, read, reset, write, data_in, addressR, addressW, data_out);
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  input [2:0] addressR;
  input [2:0] addressW;
  input clk;
  input [4:0] data_in;
  output [4:0] data_out;
  wire [4:0] \mem[0] ;
  wire [4:0] \mem[1] ;
  wire [4:0] \mem[2] ;
  wire [4:0] \mem[3] ;
  wire [4:0] \mem[4] ;
  wire [4:0] \mem[5] ;
  wire [4:0] \mem[6] ;
  wire [4:0] \mem[7] ;
  input read;
  input reset;
  input write;
  NOT _297_ (
    .A(addressR[0]),
    .Y(_003_)
  );
  NOT _298_ (
    .A(addressR[1]),
    .Y(_004_)
  );
  NOT _299_ (
    .A(write),
    .Y(_005_)
  );
  NOT _300_ (
    .A(reset),
    .Y(_006_)
  );
  NOT _301_ (
    .A(data_in[0]),
    .Y(_007_)
  );
  NOT _302_ (
    .A(data_in[1]),
    .Y(_008_)
  );
  NOT _303_ (
    .A(data_in[2]),
    .Y(_009_)
  );
  NOT _304_ (
    .A(data_in[3]),
    .Y(_010_)
  );
  NOT _305_ (
    .A(data_in[4]),
    .Y(_011_)
  );
  NOT _306_ (
    .A(addressR[2]),
    .Y(_012_)
  );
  NOT _307_ (
    .A(addressW[0]),
    .Y(_013_)
  );
  NOT _308_ (
    .A(addressW[1]),
    .Y(_014_)
  );
  NOT _309_ (
    .A(addressW[2]),
    .Y(_015_)
  );
  NOT _310_ (
    .A(read),
    .Y(_016_)
  );
  NOR _311_ (
    .A(_005_),
    .B(reset),
    .Y(_017_)
  );
  NAND _312_ (
    .A(write),
    .B(_006_),
    .Y(_018_)
  );
  NOR _313_ (
    .A(_015_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _314_ (
    .A(addressW[2]),
    .B(_017_),
    .Y(_020_)
  );
  NOR _315_ (
    .A(_014_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _316_ (
    .A(addressW[1]),
    .B(_019_),
    .Y(_022_)
  );
  NOR _317_ (
    .A(addressW[0]),
    .B(_022_),
    .Y(_023_)
  );
  NAND _318_ (
    .A(_013_),
    .B(_021_),
    .Y(_024_)
  );
  NAND _319_ (
    .A(\mem[6] [0]),
    .B(_024_),
    .Y(_025_)
  );
  NOR _320_ (
    .A(_007_),
    .B(_018_),
    .Y(_026_)
  );
  NAND _321_ (
    .A(_023_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _322_ (
    .A(_025_),
    .B(_027_),
    .Y(_186_)
  );
  NAND _323_ (
    .A(\mem[6] [1]),
    .B(_024_),
    .Y(_028_)
  );
  NOR _324_ (
    .A(_008_),
    .B(_018_),
    .Y(_029_)
  );
  NAND _325_ (
    .A(_023_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _326_ (
    .A(_028_),
    .B(_030_),
    .Y(_207_)
  );
  NAND _327_ (
    .A(\mem[6] [2]),
    .B(_024_),
    .Y(_031_)
  );
  NOR _328_ (
    .A(_009_),
    .B(_018_),
    .Y(_032_)
  );
  NAND _329_ (
    .A(_023_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _330_ (
    .A(_031_),
    .B(_033_),
    .Y(_227_)
  );
  NAND _331_ (
    .A(\mem[6] [3]),
    .B(_024_),
    .Y(_034_)
  );
  NOR _332_ (
    .A(_010_),
    .B(_018_),
    .Y(_035_)
  );
  NAND _333_ (
    .A(_023_),
    .B(_035_),
    .Y(_036_)
  );
  NAND _334_ (
    .A(_034_),
    .B(_036_),
    .Y(_247_)
  );
  NAND _335_ (
    .A(\mem[6] [4]),
    .B(_024_),
    .Y(_037_)
  );
  NOR _336_ (
    .A(_011_),
    .B(_018_),
    .Y(_038_)
  );
  NAND _337_ (
    .A(_023_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _338_ (
    .A(_037_),
    .B(_039_),
    .Y(_263_)
  );
  NOR _339_ (
    .A(addressW[1]),
    .B(_020_),
    .Y(_040_)
  );
  NAND _340_ (
    .A(_014_),
    .B(_019_),
    .Y(_041_)
  );
  NOR _341_ (
    .A(_013_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _342_ (
    .A(addressW[0]),
    .B(_040_),
    .Y(_043_)
  );
  NAND _343_ (
    .A(\mem[5] [0]),
    .B(_043_),
    .Y(_044_)
  );
  NAND _344_ (
    .A(_026_),
    .B(_042_),
    .Y(_045_)
  );
  NAND _345_ (
    .A(_044_),
    .B(_045_),
    .Y(_264_)
  );
  NAND _346_ (
    .A(\mem[5] [1]),
    .B(_043_),
    .Y(_046_)
  );
  NAND _347_ (
    .A(_029_),
    .B(_042_),
    .Y(_047_)
  );
  NAND _348_ (
    .A(_046_),
    .B(_047_),
    .Y(_265_)
  );
  NAND _349_ (
    .A(\mem[5] [2]),
    .B(_043_),
    .Y(_048_)
  );
  NAND _350_ (
    .A(_032_),
    .B(_042_),
    .Y(_049_)
  );
  NAND _351_ (
    .A(_048_),
    .B(_049_),
    .Y(_266_)
  );
  NAND _352_ (
    .A(\mem[5] [3]),
    .B(_043_),
    .Y(_050_)
  );
  NAND _353_ (
    .A(_035_),
    .B(_042_),
    .Y(_051_)
  );
  NAND _354_ (
    .A(_050_),
    .B(_051_),
    .Y(_267_)
  );
  NAND _355_ (
    .A(\mem[5] [4]),
    .B(_043_),
    .Y(_052_)
  );
  NAND _356_ (
    .A(_038_),
    .B(_042_),
    .Y(_053_)
  );
  NAND _357_ (
    .A(_052_),
    .B(_053_),
    .Y(_268_)
  );
  NOR _358_ (
    .A(_013_),
    .B(_022_),
    .Y(_054_)
  );
  NAND _359_ (
    .A(addressW[0]),
    .B(_021_),
    .Y(_055_)
  );
  NAND _360_ (
    .A(\mem[7] [0]),
    .B(_055_),
    .Y(_056_)
  );
  NAND _361_ (
    .A(_026_),
    .B(_054_),
    .Y(_057_)
  );
  NAND _362_ (
    .A(_056_),
    .B(_057_),
    .Y(_269_)
  );
  NAND _363_ (
    .A(\mem[7] [1]),
    .B(_055_),
    .Y(_058_)
  );
  NAND _364_ (
    .A(_029_),
    .B(_054_),
    .Y(_059_)
  );
  NAND _365_ (
    .A(_058_),
    .B(_059_),
    .Y(_270_)
  );
  NAND _366_ (
    .A(\mem[7] [2]),
    .B(_055_),
    .Y(_060_)
  );
  NAND _367_ (
    .A(_032_),
    .B(_054_),
    .Y(_061_)
  );
  NAND _368_ (
    .A(_060_),
    .B(_061_),
    .Y(_271_)
  );
  NAND _369_ (
    .A(\mem[7] [3]),
    .B(_055_),
    .Y(_062_)
  );
  NAND _370_ (
    .A(_035_),
    .B(_054_),
    .Y(_063_)
  );
  NAND _371_ (
    .A(_062_),
    .B(_063_),
    .Y(_272_)
  );
  NAND _372_ (
    .A(\mem[7] [4]),
    .B(_055_),
    .Y(_064_)
  );
  NAND _373_ (
    .A(_038_),
    .B(_054_),
    .Y(_065_)
  );
  NAND _374_ (
    .A(_064_),
    .B(_065_),
    .Y(_273_)
  );
  NOR _375_ (
    .A(addressW[0]),
    .B(_041_),
    .Y(_066_)
  );
  NAND _376_ (
    .A(_013_),
    .B(_040_),
    .Y(_067_)
  );
  NAND _377_ (
    .A(\mem[4] [0]),
    .B(_067_),
    .Y(_068_)
  );
  NAND _378_ (
    .A(_026_),
    .B(_066_),
    .Y(_069_)
  );
  NAND _379_ (
    .A(_068_),
    .B(_069_),
    .Y(_274_)
  );
  NAND _380_ (
    .A(\mem[4] [1]),
    .B(_067_),
    .Y(_070_)
  );
  NAND _381_ (
    .A(_029_),
    .B(_066_),
    .Y(_071_)
  );
  NAND _382_ (
    .A(_070_),
    .B(_071_),
    .Y(_275_)
  );
  NAND _383_ (
    .A(\mem[4] [2]),
    .B(_067_),
    .Y(_072_)
  );
  NAND _384_ (
    .A(_032_),
    .B(_066_),
    .Y(_073_)
  );
  NAND _385_ (
    .A(_072_),
    .B(_073_),
    .Y(_276_)
  );
  NAND _386_ (
    .A(\mem[4] [3]),
    .B(_067_),
    .Y(_074_)
  );
  NAND _387_ (
    .A(_035_),
    .B(_066_),
    .Y(_075_)
  );
  NAND _388_ (
    .A(_074_),
    .B(_075_),
    .Y(_277_)
  );
  NAND _389_ (
    .A(\mem[4] [4]),
    .B(_067_),
    .Y(_076_)
  );
  NAND _390_ (
    .A(_038_),
    .B(_066_),
    .Y(_077_)
  );
  NAND _391_ (
    .A(_076_),
    .B(_077_),
    .Y(_278_)
  );
  NOR _392_ (
    .A(_014_),
    .B(addressW[2]),
    .Y(_078_)
  );
  NAND _393_ (
    .A(addressW[1]),
    .B(_015_),
    .Y(_079_)
  );
  NOR _394_ (
    .A(_018_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _395_ (
    .A(_017_),
    .B(_078_),
    .Y(_081_)
  );
  NOR _396_ (
    .A(_013_),
    .B(_081_),
    .Y(_082_)
  );
  NAND _397_ (
    .A(addressW[0]),
    .B(_080_),
    .Y(_083_)
  );
  NAND _398_ (
    .A(\mem[3] [0]),
    .B(_083_),
    .Y(_084_)
  );
  NAND _399_ (
    .A(_026_),
    .B(_082_),
    .Y(_085_)
  );
  NAND _400_ (
    .A(_084_),
    .B(_085_),
    .Y(_279_)
  );
  NAND _401_ (
    .A(\mem[3] [1]),
    .B(_083_),
    .Y(_086_)
  );
  NAND _402_ (
    .A(_029_),
    .B(_082_),
    .Y(_087_)
  );
  NAND _403_ (
    .A(_086_),
    .B(_087_),
    .Y(_280_)
  );
  NAND _404_ (
    .A(\mem[3] [2]),
    .B(_083_),
    .Y(_088_)
  );
  NAND _405_ (
    .A(_032_),
    .B(_082_),
    .Y(_089_)
  );
  NAND _406_ (
    .A(_088_),
    .B(_089_),
    .Y(_281_)
  );
  NAND _407_ (
    .A(\mem[3] [3]),
    .B(_083_),
    .Y(_090_)
  );
  NAND _408_ (
    .A(_035_),
    .B(_082_),
    .Y(_091_)
  );
  NAND _409_ (
    .A(_090_),
    .B(_091_),
    .Y(_282_)
  );
  NAND _410_ (
    .A(\mem[3] [4]),
    .B(_083_),
    .Y(_092_)
  );
  NAND _411_ (
    .A(_038_),
    .B(_082_),
    .Y(_093_)
  );
  NAND _412_ (
    .A(_092_),
    .B(_093_),
    .Y(_283_)
  );
  NOR _413_ (
    .A(addressW[0]),
    .B(_081_),
    .Y(_094_)
  );
  NAND _414_ (
    .A(_013_),
    .B(_080_),
    .Y(_095_)
  );
  NAND _415_ (
    .A(\mem[2] [0]),
    .B(_095_),
    .Y(_096_)
  );
  NAND _416_ (
    .A(_026_),
    .B(_094_),
    .Y(_097_)
  );
  NAND _417_ (
    .A(_096_),
    .B(_097_),
    .Y(_284_)
  );
  NAND _418_ (
    .A(\mem[2] [1]),
    .B(_095_),
    .Y(_098_)
  );
  NAND _419_ (
    .A(_029_),
    .B(_094_),
    .Y(_099_)
  );
  NAND _420_ (
    .A(_098_),
    .B(_099_),
    .Y(_285_)
  );
  NAND _421_ (
    .A(\mem[2] [2]),
    .B(_095_),
    .Y(_100_)
  );
  NAND _422_ (
    .A(_032_),
    .B(_094_),
    .Y(_101_)
  );
  NAND _423_ (
    .A(_100_),
    .B(_101_),
    .Y(_286_)
  );
  NAND _424_ (
    .A(\mem[2] [3]),
    .B(_095_),
    .Y(_102_)
  );
  NAND _425_ (
    .A(_035_),
    .B(_094_),
    .Y(_103_)
  );
  NAND _426_ (
    .A(_102_),
    .B(_103_),
    .Y(_287_)
  );
  NAND _427_ (
    .A(\mem[2] [4]),
    .B(_095_),
    .Y(_104_)
  );
  NAND _428_ (
    .A(_038_),
    .B(_094_),
    .Y(_105_)
  );
  NAND _429_ (
    .A(_104_),
    .B(_105_),
    .Y(_288_)
  );
  NOR _430_ (
    .A(addressW[1]),
    .B(addressW[2]),
    .Y(_106_)
  );
  NAND _431_ (
    .A(_014_),
    .B(_015_),
    .Y(_107_)
  );
  NOR _432_ (
    .A(_018_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _433_ (
    .A(_017_),
    .B(_106_),
    .Y(_109_)
  );
  NOR _434_ (
    .A(_013_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _435_ (
    .A(addressW[0]),
    .B(_108_),
    .Y(_111_)
  );
  NAND _436_ (
    .A(data_in[0]),
    .B(_110_),
    .Y(_112_)
  );
  NAND _437_ (
    .A(\mem[1] [0]),
    .B(_111_),
    .Y(_113_)
  );
  NAND _438_ (
    .A(_112_),
    .B(_113_),
    .Y(_289_)
  );
  NAND _439_ (
    .A(data_in[1]),
    .B(_110_),
    .Y(_114_)
  );
  NAND _440_ (
    .A(\mem[1] [1]),
    .B(_111_),
    .Y(_115_)
  );
  NAND _441_ (
    .A(_114_),
    .B(_115_),
    .Y(_290_)
  );
  NAND _442_ (
    .A(data_in[2]),
    .B(_110_),
    .Y(_116_)
  );
  NAND _443_ (
    .A(\mem[1] [2]),
    .B(_111_),
    .Y(_117_)
  );
  NAND _444_ (
    .A(_116_),
    .B(_117_),
    .Y(_291_)
  );
  NAND _445_ (
    .A(data_in[3]),
    .B(_110_),
    .Y(_118_)
  );
  NAND _446_ (
    .A(\mem[1] [3]),
    .B(_111_),
    .Y(_119_)
  );
  NAND _447_ (
    .A(_118_),
    .B(_119_),
    .Y(_292_)
  );
  NAND _448_ (
    .A(data_in[4]),
    .B(_110_),
    .Y(_120_)
  );
  NAND _449_ (
    .A(\mem[1] [4]),
    .B(_111_),
    .Y(_121_)
  );
  NAND _450_ (
    .A(_120_),
    .B(_121_),
    .Y(_293_)
  );
  NOR _451_ (
    .A(addressW[0]),
    .B(_109_),
    .Y(_122_)
  );
  NAND _452_ (
    .A(_013_),
    .B(_108_),
    .Y(_123_)
  );
  NAND _453_ (
    .A(data_in[0]),
    .B(_122_),
    .Y(_124_)
  );
  NAND _454_ (
    .A(\mem[0] [0]),
    .B(_123_),
    .Y(_125_)
  );
  NAND _455_ (
    .A(_124_),
    .B(_125_),
    .Y(_294_)
  );
  NAND _456_ (
    .A(data_in[1]),
    .B(_122_),
    .Y(_126_)
  );
  NAND _457_ (
    .A(\mem[0] [1]),
    .B(_123_),
    .Y(_127_)
  );
  NAND _458_ (
    .A(_126_),
    .B(_127_),
    .Y(_295_)
  );
  NAND _459_ (
    .A(data_in[2]),
    .B(_122_),
    .Y(_128_)
  );
  NAND _460_ (
    .A(\mem[0] [2]),
    .B(_123_),
    .Y(_129_)
  );
  NAND _461_ (
    .A(_128_),
    .B(_129_),
    .Y(_296_)
  );
  NAND _462_ (
    .A(data_in[3]),
    .B(_122_),
    .Y(_130_)
  );
  NAND _463_ (
    .A(\mem[0] [3]),
    .B(_123_),
    .Y(_131_)
  );
  NAND _464_ (
    .A(_130_),
    .B(_131_),
    .Y(_001_)
  );
  NAND _465_ (
    .A(data_in[4]),
    .B(_122_),
    .Y(_132_)
  );
  NAND _466_ (
    .A(\mem[0] [4]),
    .B(_123_),
    .Y(_133_)
  );
  NAND _467_ (
    .A(_132_),
    .B(_133_),
    .Y(_002_)
  );
  NOR _468_ (
    .A(_003_),
    .B(\mem[7] [0]),
    .Y(_134_)
  );
  NOR _469_ (
    .A(addressR[0]),
    .B(\mem[6] [0]),
    .Y(_135_)
  );
  NOR _470_ (
    .A(_134_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _471_ (
    .A(_004_),
    .B(_136_),
    .Y(_137_)
  );
  NOR _472_ (
    .A(\mem[5] [0]),
    .B(_003_),
    .Y(_138_)
  );
  NOR _473_ (
    .A(\mem[4] [0]),
    .B(addressR[0]),
    .Y(_139_)
  );
  NOR _474_ (
    .A(_138_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _475_ (
    .A(addressR[1]),
    .B(_140_),
    .Y(_141_)
  );
  NOR _476_ (
    .A(_137_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _477_ (
    .A(_012_),
    .B(_142_),
    .Y(_143_)
  );
  NOR _478_ (
    .A(_003_),
    .B(\mem[3] [0]),
    .Y(_144_)
  );
  NOR _479_ (
    .A(addressR[0]),
    .B(\mem[2] [0]),
    .Y(_145_)
  );
  NOR _480_ (
    .A(_144_),
    .B(_145_),
    .Y(_146_)
  );
  NOR _481_ (
    .A(_004_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _482_ (
    .A(_003_),
    .B(\mem[1] [0]),
    .Y(_148_)
  );
  NOR _483_ (
    .A(addressR[0]),
    .B(\mem[0] [0]),
    .Y(_149_)
  );
  NOR _484_ (
    .A(_148_),
    .B(_149_),
    .Y(_150_)
  );
  NOR _485_ (
    .A(addressR[1]),
    .B(_150_),
    .Y(_151_)
  );
  NOR _486_ (
    .A(_147_),
    .B(_151_),
    .Y(_152_)
  );
  NOR _487_ (
    .A(addressR[2]),
    .B(_152_),
    .Y(_153_)
  );
  NOR _488_ (
    .A(_143_),
    .B(_153_),
    .Y(_154_)
  );
  NOR _489_ (
    .A(_016_),
    .B(_154_),
    .Y(_155_)
  );
  NOR _490_ (
    .A(data_out[0]),
    .B(read),
    .Y(_156_)
  );
  NOR _491_ (
    .A(reset),
    .B(_156_),
    .Y(_157_)
  );
  NOT _492_ (
    .A(_157_),
    .Y(_158_)
  );
  NOR _493_ (
    .A(_155_),
    .B(_158_),
    .Y(_000_[0])
  );
  NOR _494_ (
    .A(_003_),
    .B(\mem[7] [1]),
    .Y(_159_)
  );
  NOR _495_ (
    .A(addressR[0]),
    .B(\mem[6] [1]),
    .Y(_160_)
  );
  NOR _496_ (
    .A(_159_),
    .B(_160_),
    .Y(_161_)
  );
  NOR _497_ (
    .A(_004_),
    .B(_161_),
    .Y(_162_)
  );
  NOR _498_ (
    .A(_003_),
    .B(\mem[5] [1]),
    .Y(_163_)
  );
  NOR _499_ (
    .A(addressR[0]),
    .B(\mem[4] [1]),
    .Y(_164_)
  );
  NOR _500_ (
    .A(_163_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _501_ (
    .A(addressR[1]),
    .B(_165_),
    .Y(_166_)
  );
  NOR _502_ (
    .A(_162_),
    .B(_166_),
    .Y(_167_)
  );
  NOR _503_ (
    .A(_012_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _504_ (
    .A(_003_),
    .B(\mem[3] [1]),
    .Y(_169_)
  );
  NOR _505_ (
    .A(addressR[0]),
    .B(\mem[2] [1]),
    .Y(_170_)
  );
  NOR _506_ (
    .A(_169_),
    .B(_170_),
    .Y(_171_)
  );
  NOR _507_ (
    .A(_004_),
    .B(_171_),
    .Y(_172_)
  );
  NOR _508_ (
    .A(_003_),
    .B(\mem[1] [1]),
    .Y(_173_)
  );
  NOR _509_ (
    .A(addressR[0]),
    .B(\mem[0] [1]),
    .Y(_174_)
  );
  NOR _510_ (
    .A(_173_),
    .B(_174_),
    .Y(_175_)
  );
  NOR _511_ (
    .A(addressR[1]),
    .B(_175_),
    .Y(_176_)
  );
  NOR _512_ (
    .A(_172_),
    .B(_176_),
    .Y(_177_)
  );
  NOR _513_ (
    .A(addressR[2]),
    .B(_177_),
    .Y(_178_)
  );
  NOR _514_ (
    .A(_168_),
    .B(_178_),
    .Y(_179_)
  );
  NOR _515_ (
    .A(_016_),
    .B(_179_),
    .Y(_180_)
  );
  NOR _516_ (
    .A(read),
    .B(data_out[1]),
    .Y(_181_)
  );
  NOR _517_ (
    .A(reset),
    .B(_181_),
    .Y(_182_)
  );
  NOT _518_ (
    .A(_182_),
    .Y(_183_)
  );
  NOR _519_ (
    .A(_180_),
    .B(_183_),
    .Y(_000_[1])
  );
  NOR _520_ (
    .A(_003_),
    .B(\mem[7] [2]),
    .Y(_184_)
  );
  NOR _521_ (
    .A(addressR[0]),
    .B(\mem[6] [2]),
    .Y(_185_)
  );
  NOR _522_ (
    .A(_184_),
    .B(_185_),
    .Y(_187_)
  );
  NOR _523_ (
    .A(_004_),
    .B(_187_),
    .Y(_188_)
  );
  NOR _524_ (
    .A(_003_),
    .B(\mem[5] [2]),
    .Y(_189_)
  );
  NOR _525_ (
    .A(addressR[0]),
    .B(\mem[4] [2]),
    .Y(_190_)
  );
  NOR _526_ (
    .A(_189_),
    .B(_190_),
    .Y(_191_)
  );
  NOR _527_ (
    .A(addressR[1]),
    .B(_191_),
    .Y(_192_)
  );
  NOR _528_ (
    .A(_188_),
    .B(_192_),
    .Y(_193_)
  );
  NOR _529_ (
    .A(_012_),
    .B(_193_),
    .Y(_194_)
  );
  NOR _530_ (
    .A(_003_),
    .B(\mem[3] [2]),
    .Y(_195_)
  );
  NOR _531_ (
    .A(addressR[0]),
    .B(\mem[2] [2]),
    .Y(_196_)
  );
  NOR _532_ (
    .A(_195_),
    .B(_196_),
    .Y(_197_)
  );
  NOR _533_ (
    .A(_004_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _534_ (
    .A(_003_),
    .B(\mem[1] [2]),
    .Y(_199_)
  );
  NOR _535_ (
    .A(addressR[0]),
    .B(\mem[0] [2]),
    .Y(_200_)
  );
  NOR _536_ (
    .A(_199_),
    .B(_200_),
    .Y(_201_)
  );
  NOR _537_ (
    .A(addressR[1]),
    .B(_201_),
    .Y(_202_)
  );
  NOR _538_ (
    .A(_198_),
    .B(_202_),
    .Y(_203_)
  );
  NOR _539_ (
    .A(addressR[2]),
    .B(_203_),
    .Y(_204_)
  );
  NOR _540_ (
    .A(_194_),
    .B(_204_),
    .Y(_205_)
  );
  NOR _541_ (
    .A(_016_),
    .B(_205_),
    .Y(_206_)
  );
  NOR _542_ (
    .A(read),
    .B(data_out[2]),
    .Y(_208_)
  );
  NOR _543_ (
    .A(reset),
    .B(_208_),
    .Y(_209_)
  );
  NOT _544_ (
    .A(_209_),
    .Y(_210_)
  );
  NOR _545_ (
    .A(_206_),
    .B(_210_),
    .Y(_000_[2])
  );
  NOR _546_ (
    .A(_003_),
    .B(\mem[7] [3]),
    .Y(_211_)
  );
  NOR _547_ (
    .A(addressR[0]),
    .B(\mem[6] [3]),
    .Y(_212_)
  );
  NOR _548_ (
    .A(_211_),
    .B(_212_),
    .Y(_213_)
  );
  NOR _549_ (
    .A(_004_),
    .B(_213_),
    .Y(_214_)
  );
  NOR _550_ (
    .A(_003_),
    .B(\mem[5] [3]),
    .Y(_215_)
  );
  NOR _551_ (
    .A(addressR[0]),
    .B(\mem[4] [3]),
    .Y(_216_)
  );
  NOR _552_ (
    .A(_215_),
    .B(_216_),
    .Y(_217_)
  );
  NOR _553_ (
    .A(addressR[1]),
    .B(_217_),
    .Y(_218_)
  );
  NOR _554_ (
    .A(_214_),
    .B(_218_),
    .Y(_219_)
  );
  NOR _555_ (
    .A(_012_),
    .B(_219_),
    .Y(_220_)
  );
  NOR _556_ (
    .A(_003_),
    .B(\mem[3] [3]),
    .Y(_221_)
  );
  NOR _557_ (
    .A(addressR[0]),
    .B(\mem[2] [3]),
    .Y(_222_)
  );
  NOR _558_ (
    .A(_221_),
    .B(_222_),
    .Y(_223_)
  );
  NOR _559_ (
    .A(_004_),
    .B(_223_),
    .Y(_224_)
  );
  NOR _560_ (
    .A(_003_),
    .B(\mem[1] [3]),
    .Y(_225_)
  );
  NOR _561_ (
    .A(addressR[0]),
    .B(\mem[0] [3]),
    .Y(_226_)
  );
  NOR _562_ (
    .A(_225_),
    .B(_226_),
    .Y(_228_)
  );
  NOR _563_ (
    .A(addressR[1]),
    .B(_228_),
    .Y(_229_)
  );
  NOR _564_ (
    .A(_224_),
    .B(_229_),
    .Y(_230_)
  );
  NOR _565_ (
    .A(addressR[2]),
    .B(_230_),
    .Y(_231_)
  );
  NOR _566_ (
    .A(_220_),
    .B(_231_),
    .Y(_232_)
  );
  NOR _567_ (
    .A(_016_),
    .B(_232_),
    .Y(_233_)
  );
  NOR _568_ (
    .A(read),
    .B(data_out[3]),
    .Y(_234_)
  );
  NOR _569_ (
    .A(reset),
    .B(_234_),
    .Y(_235_)
  );
  NOT _570_ (
    .A(_235_),
    .Y(_236_)
  );
  NOR _571_ (
    .A(_233_),
    .B(_236_),
    .Y(_000_[3])
  );
  NOR _572_ (
    .A(_003_),
    .B(\mem[7] [4]),
    .Y(_237_)
  );
  NOR _573_ (
    .A(addressR[0]),
    .B(\mem[6] [4]),
    .Y(_238_)
  );
  NOR _574_ (
    .A(_237_),
    .B(_238_),
    .Y(_239_)
  );
  NOR _575_ (
    .A(_004_),
    .B(_239_),
    .Y(_240_)
  );
  NOR _576_ (
    .A(_003_),
    .B(\mem[5] [4]),
    .Y(_241_)
  );
  NOR _577_ (
    .A(addressR[0]),
    .B(\mem[4] [4]),
    .Y(_242_)
  );
  NOR _578_ (
    .A(_241_),
    .B(_242_),
    .Y(_243_)
  );
  NOR _579_ (
    .A(addressR[1]),
    .B(_243_),
    .Y(_244_)
  );
  NOR _580_ (
    .A(_240_),
    .B(_244_),
    .Y(_245_)
  );
  NOR _581_ (
    .A(_012_),
    .B(_245_),
    .Y(_246_)
  );
  NOR _582_ (
    .A(_003_),
    .B(\mem[3] [4]),
    .Y(_248_)
  );
  NOR _583_ (
    .A(addressR[0]),
    .B(\mem[2] [4]),
    .Y(_249_)
  );
  NOR _584_ (
    .A(_248_),
    .B(_249_),
    .Y(_250_)
  );
  NOR _585_ (
    .A(_004_),
    .B(_250_),
    .Y(_251_)
  );
  NOR _586_ (
    .A(_003_),
    .B(\mem[1] [4]),
    .Y(_252_)
  );
  NOR _587_ (
    .A(addressR[0]),
    .B(\mem[0] [4]),
    .Y(_253_)
  );
  NOR _588_ (
    .A(_252_),
    .B(_253_),
    .Y(_254_)
  );
  NOR _589_ (
    .A(addressR[1]),
    .B(_254_),
    .Y(_255_)
  );
  NOR _590_ (
    .A(_251_),
    .B(_255_),
    .Y(_256_)
  );
  NOR _591_ (
    .A(addressR[2]),
    .B(_256_),
    .Y(_257_)
  );
  NOR _592_ (
    .A(_246_),
    .B(_257_),
    .Y(_258_)
  );
  NOR _593_ (
    .A(_016_),
    .B(_258_),
    .Y(_259_)
  );
  NOR _594_ (
    .A(read),
    .B(data_out[4]),
    .Y(_260_)
  );
  NOR _595_ (
    .A(reset),
    .B(_260_),
    .Y(_261_)
  );
  NOT _596_ (
    .A(_261_),
    .Y(_262_)
  );
  NOR _597_ (
    .A(_259_),
    .B(_262_),
    .Y(_000_[4])
  );
  DFF _598_ (
    .C(clk),
    .D(_294_),
    .Q(\mem[0] [0])
  );
  DFF _599_ (
    .C(clk),
    .D(_295_),
    .Q(\mem[0] [1])
  );
  DFF _600_ (
    .C(clk),
    .D(_296_),
    .Q(\mem[0] [2])
  );
  DFF _601_ (
    .C(clk),
    .D(_001_),
    .Q(\mem[0] [3])
  );
  DFF _602_ (
    .C(clk),
    .D(_002_),
    .Q(\mem[0] [4])
  );
  DFF _603_ (
    .C(clk),
    .D(_289_),
    .Q(\mem[1] [0])
  );
  DFF _604_ (
    .C(clk),
    .D(_290_),
    .Q(\mem[1] [1])
  );
  DFF _605_ (
    .C(clk),
    .D(_291_),
    .Q(\mem[1] [2])
  );
  DFF _606_ (
    .C(clk),
    .D(_292_),
    .Q(\mem[1] [3])
  );
  DFF _607_ (
    .C(clk),
    .D(_293_),
    .Q(\mem[1] [4])
  );
  DFF _608_ (
    .C(clk),
    .D(_264_),
    .Q(\mem[5] [0])
  );
  DFF _609_ (
    .C(clk),
    .D(_265_),
    .Q(\mem[5] [1])
  );
  DFF _610_ (
    .C(clk),
    .D(_266_),
    .Q(\mem[5] [2])
  );
  DFF _611_ (
    .C(clk),
    .D(_267_),
    .Q(\mem[5] [3])
  );
  DFF _612_ (
    .C(clk),
    .D(_268_),
    .Q(\mem[5] [4])
  );
  DFF _613_ (
    .C(clk),
    .D(_279_),
    .Q(\mem[3] [0])
  );
  DFF _614_ (
    .C(clk),
    .D(_280_),
    .Q(\mem[3] [1])
  );
  DFF _615_ (
    .C(clk),
    .D(_281_),
    .Q(\mem[3] [2])
  );
  DFF _616_ (
    .C(clk),
    .D(_282_),
    .Q(\mem[3] [3])
  );
  DFF _617_ (
    .C(clk),
    .D(_283_),
    .Q(\mem[3] [4])
  );
  DFF _618_ (
    .C(clk),
    .D(_274_),
    .Q(\mem[4] [0])
  );
  DFF _619_ (
    .C(clk),
    .D(_275_),
    .Q(\mem[4] [1])
  );
  DFF _620_ (
    .C(clk),
    .D(_276_),
    .Q(\mem[4] [2])
  );
  DFF _621_ (
    .C(clk),
    .D(_277_),
    .Q(\mem[4] [3])
  );
  DFF _622_ (
    .C(clk),
    .D(_278_),
    .Q(\mem[4] [4])
  );
  DFF _623_ (
    .C(clk),
    .D(_284_),
    .Q(\mem[2] [0])
  );
  DFF _624_ (
    .C(clk),
    .D(_285_),
    .Q(\mem[2] [1])
  );
  DFF _625_ (
    .C(clk),
    .D(_286_),
    .Q(\mem[2] [2])
  );
  DFF _626_ (
    .C(clk),
    .D(_287_),
    .Q(\mem[2] [3])
  );
  DFF _627_ (
    .C(clk),
    .D(_288_),
    .Q(\mem[2] [4])
  );
  DFF _628_ (
    .C(clk),
    .D(_269_),
    .Q(\mem[7] [0])
  );
  DFF _629_ (
    .C(clk),
    .D(_270_),
    .Q(\mem[7] [1])
  );
  DFF _630_ (
    .C(clk),
    .D(_271_),
    .Q(\mem[7] [2])
  );
  DFF _631_ (
    .C(clk),
    .D(_272_),
    .Q(\mem[7] [3])
  );
  DFF _632_ (
    .C(clk),
    .D(_273_),
    .Q(\mem[7] [4])
  );
  DFF _633_ (
    .C(clk),
    .D(_186_),
    .Q(\mem[6] [0])
  );
  DFF _634_ (
    .C(clk),
    .D(_207_),
    .Q(\mem[6] [1])
  );
  DFF _635_ (
    .C(clk),
    .D(_227_),
    .Q(\mem[6] [2])
  );
  DFF _636_ (
    .C(clk),
    .D(_247_),
    .Q(\mem[6] [3])
  );
  DFF _637_ (
    .C(clk),
    .D(_263_),
    .Q(\mem[6] [4])
  );
  DFF _638_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  DFF _639_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  DFF _640_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  DFF _641_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  DFF _642_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_out[4])
  );
endmodule

module roundRobin_Synth(clk, reset_L, request0, request1, portMux, validMux, pop_0, pop_1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  input clk;
  output pop_0;
  output pop_1;
  output portMux;
  input request0;
  input request1;
  input reset_L;
  output validMux;
  NOT _12_ (
    .A(request0),
    .Y(_11_)
  );
  NOT _13_ (
    .A(reset_L),
    .Y(_02_)
  );
  NOR _14_ (
    .A(_11_),
    .B(portMux),
    .Y(_03_)
  );
  NAND _15_ (
    .A(request1),
    .B(_02_),
    .Y(_04_)
  );
  NOR _16_ (
    .A(_03_),
    .B(_04_),
    .Y(pop_1)
  );
  NAND _17_ (
    .A(request1),
    .B(portMux),
    .Y(_05_)
  );
  NOT _18_ (
    .A(_05_),
    .Y(_06_)
  );
  NAND _19_ (
    .A(request0),
    .B(_02_),
    .Y(_07_)
  );
  NOR _20_ (
    .A(_06_),
    .B(_07_),
    .Y(pop_0)
  );
  NAND _21_ (
    .A(_11_),
    .B(_02_),
    .Y(_08_)
  );
  NOR _22_ (
    .A(request1),
    .B(_08_),
    .Y(_01_)
  );
  NAND _23_ (
    .A(request0),
    .B(portMux),
    .Y(_09_)
  );
  NOT _24_ (
    .A(_09_),
    .Y(_10_)
  );
  NOR _25_ (
    .A(_04_),
    .B(_10_),
    .Y(_00_)
  );
  DFF _26_ (
    .C(clk),
    .D(_00_),
    .Q(portMux)
  );
  DFF _27_ (
    .C(clk),
    .D(_01_),
    .Q(validMux)
  );
endmodule
